[tool.poetry]
name = "ls"
version = "0.1.0"
description = ""
authors = ["Chris P <chrisp1877@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
lxml="*"
python-docx="*"
pyqt5="*"
mutagen="*"
pillow="*"

[tool.poetry.dev-dependencies]
mypy="*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
run="python3 src/main.py"
