# Form implementation generated from reading ui file 'c:\Users\chris\is\isutils\isu\ui\ops\text.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_textOp(object):
    def setupUi(self, textOp):
        textOp.setObjectName("textOp")
        textOp.resize(350, 276)
        self.verticalLayout = QtWidgets.QVBoxLayout(textOp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(textOp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 330, 206))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label_8 = QtWidgets.QLabel(textOp)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(textOp)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)

        self.retranslateUi(textOp)
        QtCore.QMetaObject.connectSlotsByName(textOp)

    def retranslateUi(self, textOp):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("textOp", "GroupBox"))
        self.label_8.setText(_translate("textOp", "Audio attachment behavior"))
        self.comboBox.setItemText(0, _translate("textOp", "Mixed section and step audio"))
        self.comboBox.setItemText(1, _translate("textOp", "Section audio only"))
        self.comboBox.setItemText(2, _translate("textOp", "Step audio only"))
