# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QHBoxLayout, QHeaderView,
    QLayout, QListWidget, QListWidgetItem, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QTabWidget, QToolButton,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_IscApp(object):
    def setupUi(self, IscApp):
        if not IscApp.objectName():
            IscApp.setObjectName(u"IscApp")
        IscApp.resize(1440, 923)
        IscApp.setCursor(QCursor(Qt.ArrowCursor))
        IscApp.setMouseTracking(True)
        self.actionUndo = QAction(IscApp)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(IscApp)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionView_statusbar = QAction(IscApp)
        self.actionView_statusbar.setObjectName(u"actionView_statusbar")
        self.actionView_statusbar.setCheckable(True)
        self.actionView_statusbar.setChecked(True)
        self.actionView_step_preview = QAction(IscApp)
        self.actionView_step_preview.setObjectName(u"actionView_step_preview")
        self.actionView_step_preview.setCheckable(True)
        self.actionView_step_preview.setChecked(True)
        self.actionInsert = QAction(IscApp)
        self.actionInsert.setObjectName(u"actionInsert")
        self.actionShell_Image = QAction(IscApp)
        self.actionShell_Image.setObjectName(u"actionShell_Image")
        self.actionSection_steps = QAction(IscApp)
        self.actionSection_steps.setObjectName(u"actionSection_steps")
        self.actionAttach_audio = QAction(IscApp)
        self.actionAttach_audio.setObjectName(u"actionAttach_audio")
        self.actionBulk_crop = QAction(IscApp)
        self.actionBulk_crop.setObjectName(u"actionBulk_crop")
        self.actionView_demo_in_folder = QAction(IscApp)
        self.actionView_demo_in_folder.setObjectName(u"actionView_demo_in_folder")
        self.actionLoad_tool_state = QAction(IscApp)
        self.actionLoad_tool_state.setObjectName(u"actionLoad_tool_state")
        self.actionSave_tool_state = QAction(IscApp)
        self.actionSave_tool_state.setObjectName(u"actionSave_tool_state")
        self.actionOpen_DemoMate = QAction(IscApp)
        self.actionOpen_DemoMate.setObjectName(u"actionOpen_DemoMate")
        self.actionOpen_Cloudguides_Packaging = QAction(IscApp)
        self.actionOpen_Cloudguides_Packaging.setObjectName(u"actionOpen_Cloudguides_Packaging")
        self.actionAbout = QAction(IscApp)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionHelp_2 = QAction(IscApp)
        self.actionHelp_2.setObjectName(u"actionHelp_2")
        self.actionImage_Insert = QAction(IscApp)
        self.actionImage_Insert.setObjectName(u"actionImage_Insert")
        self.actionImage_Shelling = QAction(IscApp)
        self.actionImage_Shelling.setObjectName(u"actionImage_Shelling")
        self.actionHelp_3 = QAction(IscApp)
        self.actionHelp_3.setObjectName(u"actionHelp_3")
        self.actionBulk_insert_image = QAction(IscApp)
        self.actionBulk_insert_image.setObjectName(u"actionBulk_insert_image")
        self.actionBulk_shell_steps = QAction(IscApp)
        self.actionBulk_shell_steps.setObjectName(u"actionBulk_shell_steps")
        self.actionBulk_crop_step_assets = QAction(IscApp)
        self.actionBulk_crop_step_assets.setObjectName(u"actionBulk_crop_step_assets")
        self.actionAttach_audio_to_demo = QAction(IscApp)
        self.actionAttach_audio_to_demo.setObjectName(u"actionAttach_audio_to_demo")
        self.actionClose = QAction(IscApp)
        self.actionClose.setObjectName(u"actionClose")
        self.actionClose_2 = QAction(IscApp)
        self.actionClose_2.setObjectName(u"actionClose_2")
        self.actionFrom_demo_file = QAction(IscApp)
        self.actionFrom_demo_file.setObjectName(u"actionFrom_demo_file")
        self.actionFrom_exe_installer = QAction(IscApp)
        self.actionFrom_exe_installer.setObjectName(u"actionFrom_exe_installer")
        self.actionFrom_docx_file = QAction(IscApp)
        self.actionFrom_docx_file.setObjectName(u"actionFrom_docx_file")
        self.actionFrom_scripts_folder = QAction(IscApp)
        self.actionFrom_scripts_folder.setObjectName(u"actionFrom_scripts_folder")
        self.actionOverwrite = QAction(IscApp)
        self.actionOverwrite.setObjectName(u"actionOverwrite")
        self.actionMerge_demos = QAction(IscApp)
        self.actionMerge_demos.setObjectName(u"actionMerge_demos")
        self.actionLoad_audio_directory = QAction(IscApp)
        self.actionLoad_audio_directory.setObjectName(u"actionLoad_audio_directory")
        self.actionLoad_soundbite = QAction(IscApp)
        self.actionLoad_soundbite.setObjectName(u"actionLoad_soundbite")
        self.actionEdit_audio = QAction(IscApp)
        self.actionEdit_audio.setObjectName(u"actionEdit_audio")
        self.actionAttach_audio_to_demo_2 = QAction(IscApp)
        self.actionAttach_audio_to_demo_2.setObjectName(u"actionAttach_audio_to_demo_2")
        self.actionBulk_edit_demo_audio = QAction(IscApp)
        self.actionBulk_edit_demo_audio.setObjectName(u"actionBulk_edit_demo_audio")
        self.actionEdit_step_audio = QAction(IscApp)
        self.actionEdit_step_audio.setObjectName(u"actionEdit_step_audio")
        self.actionBulk_paste_image = QAction(IscApp)
        self.actionBulk_paste_image.setObjectName(u"actionBulk_paste_image")
        self.actionBulk_image_paste_wizard = QAction(IscApp)
        self.actionBulk_image_paste_wizard.setObjectName(u"actionBulk_image_paste_wizard")
        self.actionBulk_shell_demo_assets = QAction(IscApp)
        self.actionBulk_shell_demo_assets.setObjectName(u"actionBulk_shell_demo_assets")
        self.actionSection_demo = QAction(IscApp)
        self.actionSection_demo.setObjectName(u"actionSection_demo")
        self.actionBulk_resize_demo_assets = QAction(IscApp)
        self.actionBulk_resize_demo_assets.setObjectName(u"actionBulk_resize_demo_assets")
        self.actionBulk_crop_demo_assets = QAction(IscApp)
        self.actionBulk_crop_demo_assets.setObjectName(u"actionBulk_crop_demo_assets")
        self.actionPacing_wizard = QAction(IscApp)
        self.actionPacing_wizard.setObjectName(u"actionPacing_wizard")
        self.actionCompose_demos = QAction(IscApp)
        self.actionCompose_demos.setObjectName(u"actionCompose_demos")
        self.actionBulk_edit_demo_metadata = QAction(IscApp)
        self.actionBulk_edit_demo_metadata.setObjectName(u"actionBulk_edit_demo_metadata")
        self.actionLoad_script = QAction(IscApp)
        self.actionLoad_script.setObjectName(u"actionLoad_script")
        self.actionConvert_script = QAction(IscApp)
        self.actionConvert_script.setObjectName(u"actionConvert_script")
        self.actionSpelling_errors = QAction(IscApp)
        self.actionSpelling_errors.setObjectName(u"actionSpelling_errors")
        self.actionGrammar_errors = QAction(IscApp)
        self.actionGrammar_errors.setObjectName(u"actionGrammar_errors")
        self.actionProduction_notes = QAction(IscApp)
        self.actionProduction_notes.setObjectName(u"actionProduction_notes")
        self.actionTalking_points = QAction(IscApp)
        self.actionTalking_points.setObjectName(u"actionTalking_points")
        self.actionClick_instructions = QAction(IscApp)
        self.actionClick_instructions.setObjectName(u"actionClick_instructions")
        self.actionPackage_demo = QAction(IscApp)
        self.actionPackage_demo.setObjectName(u"actionPackage_demo")
        self.actionSingle_image = QAction(IscApp)
        self.actionSingle_image.setObjectName(u"actionSingle_image")
        self.actionMultiple_images = QAction(IscApp)
        self.actionMultiple_images.setObjectName(u"actionMultiple_images")
        self.actionImage_insert_wizar = QAction(IscApp)
        self.actionImage_insert_wizar.setObjectName(u"actionImage_insert_wizar")
        self.actionAdd_background_image = QAction(IscApp)
        self.actionAdd_background_image.setObjectName(u"actionAdd_background_image")
        self.actionAdd_background_and_wrapper = QAction(IscApp)
        self.actionAdd_background_and_wrapper.setObjectName(u"actionAdd_background_and_wrapper")
        self.actionShell_wizard = QAction(IscApp)
        self.actionShell_wizard.setObjectName(u"actionShell_wizard")
        self.actionCrop = QAction(IscApp)
        self.actionCrop.setObjectName(u"actionCrop")
        self.actionResize = QAction(IscApp)
        self.actionResize.setObjectName(u"actionResize")
        self.actionLoad_operation = QAction(IscApp)
        self.actionLoad_operation.setObjectName(u"actionLoad_operation")
        self.actionSave_operation = QAction(IscApp)
        self.actionSave_operation.setObjectName(u"actionSave_operation")
        self.actionClose_3 = QAction(IscApp)
        self.actionClose_3.setObjectName(u"actionClose_3")
        self.actionZoom_in = QAction(IscApp)
        self.actionZoom_in.setObjectName(u"actionZoom_in")
        self.actionAdd_scroll_section = QAction(IscApp)
        self.actionAdd_scroll_section.setObjectName(u"actionAdd_scroll_section")
        self.actionOpen_assets_folder = QAction(IscApp)
        self.actionOpen_assets_folder.setObjectName(u"actionOpen_assets_folder")
        self.actionUpload_to_CloudGuides = QAction(IscApp)
        self.actionUpload_to_CloudGuides.setObjectName(u"actionUpload_to_CloudGuides")
        self.actionSections = QAction(IscApp)
        self.actionSections.setObjectName(u"actionSections")
        self.actionsteps = QAction(IscApp)
        self.actionsteps.setObjectName(u"actionsteps")
        self.actionSection = QAction(IscApp)
        self.actionSection.setObjectName(u"actionSection")
        self.actionSteps_in_section = QAction(IscApp)
        self.actionSteps_in_section.setObjectName(u"actionSteps_in_section")
        self.actionFirst_step_in_section = QAction(IscApp)
        self.actionFirst_step_in_section.setObjectName(u"actionFirst_step_in_section")
        self.actionSet_section_as_animated = QAction(IscApp)
        self.actionSet_section_as_animated.setObjectName(u"actionSet_section_as_animated")
        self.actionSet_section_as_guided = QAction(IscApp)
        self.actionSet_section_as_guided.setObjectName(u"actionSet_section_as_guided")
        self.actionDelete = QAction(IscApp)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionDuplicate = QAction(IscApp)
        self.actionDuplicate.setObjectName(u"actionDuplicate")
        self.actionDuplicate_as_pacing = QAction(IscApp)
        self.actionDuplicate_as_pacing.setObjectName(u"actionDuplicate_as_pacing")
        self.actionMove = QAction(IscApp)
        self.actionMove.setObjectName(u"actionMove")
        self.actionMove_2 = QAction(IscApp)
        self.actionMove_2.setObjectName(u"actionMove_2")
        self.actionSet_as_animated = QAction(IscApp)
        self.actionSet_as_animated.setObjectName(u"actionSet_as_animated")
        self.actionSet_as_guided = QAction(IscApp)
        self.actionSet_as_guided.setObjectName(u"actionSet_as_guided")
        self.actionSet_as_scroll = QAction(IscApp)
        self.actionSet_as_scroll.setObjectName(u"actionSet_as_scroll")
        self.actionDecrement_step_delay = QAction(IscApp)
        self.actionDecrement_step_delay.setObjectName(u"actionDecrement_step_delay")
        self.actionIncrement_step_delay = QAction(IscApp)
        self.actionIncrement_step_delay.setObjectName(u"actionIncrement_step_delay")
        self.actionAdd_audio_2 = QAction(IscApp)
        self.actionAdd_audio_2.setObjectName(u"actionAdd_audio_2")
        self.actionDelete_audio = QAction(IscApp)
        self.actionDelete_audio.setObjectName(u"actionDelete_audio")
        self.actionEdit_audio_2 = QAction(IscApp)
        self.actionEdit_audio_2.setObjectName(u"actionEdit_audio_2")
        self.actionReplace_audio = QAction(IscApp)
        self.actionReplace_audio.setObjectName(u"actionReplace_audio")
        self.actionView_metadata = QAction(IscApp)
        self.actionView_metadata.setObjectName(u"actionView_metadata")
        self.actionAdd_audio_3 = QAction(IscApp)
        self.actionAdd_audio_3.setObjectName(u"actionAdd_audio_3")
        self.actionDelete_audio_2 = QAction(IscApp)
        self.actionDelete_audio_2.setObjectName(u"actionDelete_audio_2")
        self.actionReplace_audio_2 = QAction(IscApp)
        self.actionReplace_audio_2.setObjectName(u"actionReplace_audio_2")
        self.actionEdit_audio_3 = QAction(IscApp)
        self.actionEdit_audio_3.setObjectName(u"actionEdit_audio_3")
        self.actionIncrement_step_delay_2 = QAction(IscApp)
        self.actionIncrement_step_delay_2.setObjectName(u"actionIncrement_step_delay_2")
        self.actionDecrement_step_delay_2 = QAction(IscApp)
        self.actionDecrement_step_delay_2.setObjectName(u"actionDecrement_step_delay_2")
        self.actionPreview = QAction(IscApp)
        self.actionPreview.setObjectName(u"actionPreview")
        self.actionView_in_folder = QAction(IscApp)
        self.actionView_in_folder.setObjectName(u"actionView_in_folder")
        self.actionEdit = QAction(IscApp)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionReplace_image = QAction(IscApp)
        self.actionReplace_image.setObjectName(u"actionReplace_image")
        self.actionView_metadata_2 = QAction(IscApp)
        self.actionView_metadata_2.setObjectName(u"actionView_metadata_2")
        self.actionLoad_SoundBite = QAction(IscApp)
        self.actionLoad_SoundBite.setObjectName(u"actionLoad_SoundBite")
        self.actionFrom_recording = QAction(IscApp)
        self.actionFrom_recording.setObjectName(u"actionFrom_recording")
        self.actionAs_new_version = QAction(IscApp)
        self.actionAs_new_version.setObjectName(u"actionAs_new_version")
        self.actionAs_new_round = QAction(IscApp)
        self.actionAs_new_round.setObjectName(u"actionAs_new_round")
        self.actionExport_to_installer = QAction(IscApp)
        self.actionExport_to_installer.setObjectName(u"actionExport_to_installer")
        self.actionExport_to_Cloudguide = QAction(IscApp)
        self.actionExport_to_Cloudguide.setObjectName(u"actionExport_to_Cloudguide")
        self.actionTo_installer = QAction(IscApp)
        self.actionTo_installer.setObjectName(u"actionTo_installer")
        self.actionTo_Cloudguide = QAction(IscApp)
        self.actionTo_Cloudguide.setObjectName(u"actionTo_Cloudguide")
        self.actionOverwrite_2 = QAction(IscApp)
        self.actionOverwrite_2.setObjectName(u"actionOverwrite_2")
        self.actionAs_new_version_2 = QAction(IscApp)
        self.actionAs_new_version_2.setObjectName(u"actionAs_new_version_2")
        self.actionAs_new_round_2 = QAction(IscApp)
        self.actionAs_new_round_2.setObjectName(u"actionAs_new_round_2")
        self.actionAs_txt = QAction(IscApp)
        self.actionAs_txt.setObjectName(u"actionAs_txt")
        self.actionTo_new_directory = QAction(IscApp)
        self.actionTo_new_directory.setObjectName(u"actionTo_new_directory")
        self.actionOverwrite_3 = QAction(IscApp)
        self.actionOverwrite_3.setObjectName(u"actionOverwrite_3")
        self.actionClose_window = QAction(IscApp)
        self.actionClose_window.setObjectName(u"actionClose_window")
        self.actionReset_demo = QAction(IscApp)
        self.actionReset_demo.setObjectName(u"actionReset_demo")
        self.actionNew = QAction(IscApp)
        self.actionNew.setObjectName(u"actionNew")
        self.actionNew_operation = QAction(IscApp)
        self.actionNew_operation.setObjectName(u"actionNew_operation")
        self.actionAdd_step = QAction(IscApp)
        self.actionAdd_step.setObjectName(u"actionAdd_step")
        self.actionPreferences = QAction(IscApp)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionAdd_text_box = QAction(IscApp)
        self.actionAdd_text_box.setObjectName(u"actionAdd_text_box")
        self.actionAdd_highlight = QAction(IscApp)
        self.actionAdd_highlight.setObjectName(u"actionAdd_highlight")
        self.actionAdd_jump_box = QAction(IscApp)
        self.actionAdd_jump_box.setObjectName(u"actionAdd_jump_box")
        self.actionSet_animated = QAction(IscApp)
        self.actionSet_animated.setObjectName(u"actionSet_animated")
        self.actionSet_guided = QAction(IscApp)
        self.actionSet_guided.setObjectName(u"actionSet_guided")
        self.actionEdit_XML = QAction(IscApp)
        self.actionEdit_XML.setObjectName(u"actionEdit_XML")
        self.actionFrom_capture = QAction(IscApp)
        self.actionFrom_capture.setObjectName(u"actionFrom_capture")
        self.actionCapture_image_edt_macro = QAction(IscApp)
        self.actionCapture_image_edt_macro.setObjectName(u"actionCapture_image_edt_macro")
        self.actionNew_tab = QAction(IscApp)
        self.actionNew_tab.setObjectName(u"actionNew_tab")
        self.actionNew_2 = QAction(IscApp)
        self.actionNew_2.setObjectName(u"actionNew_2")
        self.actionTo_new_version = QAction(IscApp)
        self.actionTo_new_version.setObjectName(u"actionTo_new_version")
        self.actionTo_new_round = QAction(IscApp)
        self.actionTo_new_round.setObjectName(u"actionTo_new_round")
        self.actionSteps = QAction(IscApp)
        self.actionSteps.setObjectName(u"actionSteps")
        self.actionOverwrite_existing = QAction(IscApp)
        self.actionOverwrite_existing.setObjectName(u"actionOverwrite_existing")
        self.actionSave = QAction(IscApp)
        self.actionSave.setObjectName(u"actionSave")
        self.actionDemo = QAction(IscApp)
        self.actionDemo.setObjectName(u"actionDemo")
        self.actionAudio = QAction(IscApp)
        self.actionAudio.setObjectName(u"actionAudio")
        self.actionScript = QAction(IscApp)
        self.actionScript.setObjectName(u"actionScript")
        self.actionView_menubar = QAction(IscApp)
        self.actionView_menubar.setObjectName(u"actionView_menubar")
        self.actionView_menubar.setCheckable(True)
        self.actionView_in_file_explorer = QAction(IscApp)
        self.actionView_in_file_explorer.setObjectName(u"actionView_in_file_explorer")
        self.actionView_menubar_2 = QAction(IscApp)
        self.actionView_menubar_2.setObjectName(u"actionView_menubar_2")
        self.actionView_menubar_2.setCheckable(True)
        self.actionZoom_out = QAction(IscApp)
        self.actionZoom_out.setObjectName(u"actionZoom_out")
        self.actionReset_zoom = QAction(IscApp)
        self.actionReset_zoom.setObjectName(u"actionReset_zoom")
        self.actionNewStep = QAction(IscApp)
        self.actionNewStep.setObjectName(u"actionNewStep")
        self.actionOpenDemo = QAction(IscApp)
        self.actionOpenDemo.setObjectName(u"actionOpenDemo")
        self.centralwidget = QWidget(IscApp)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_10 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.centralTabs = QTabWidget(self.centralwidget)
        self.centralTabs.setObjectName(u"centralTabs")
        self.centralTabs.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralTabs.sizePolicy().hasHeightForWidth())
        self.centralTabs.setSizePolicy(sizePolicy)
        self.centralTabs.setAcceptDrops(True)
        self.centralTabs.setAutoFillBackground(False)
        self.centralTabs.setDocumentMode(True)
        self.centralTabs.setTabsClosable(False)
        self.centralTabs.setMovable(True)
        self.centralTabs.setTabBarAutoHide(False)
        self.centralTabsPage1_2 = QWidget()
        self.centralTabsPage1_2.setObjectName(u"centralTabsPage1_2")
        self.horizontalLayout_2 = QHBoxLayout(self.centralTabsPage1_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.stepsLayout = QVBoxLayout()
        self.stepsLayout.setSpacing(10)
        self.stepsLayout.setObjectName(u"stepsLayout")
        self.stepsLayout.setSizeConstraint(QLayout.SetMaximumSize)
        self.stepsLayout.setContentsMargins(0, 0, 0, 0)
        self.assetsTabs = QTabWidget(self.centralTabsPage1_2)
        self.assetsTabs.setObjectName(u"assetsTabs")
        self.assetsTabs.setMinimumSize(QSize(362, 0))
        self.assetsTabs.setMaximumSize(QSize(410, 16777215))
        self.assetsTabs.setMouseTracking(False)
        self.assetsTabs.setLayoutDirection(Qt.LeftToRight)
        self.assetsTabs.setAutoFillBackground(False)
        self.assetsTabs.setTabPosition(QTabWidget.North)
        self.assetsTabs.setTabShape(QTabWidget.Rounded)
        self.assetsTabs.setUsesScrollButtons(False)
        self.assetsTabs.setDocumentMode(False)
        self.assetsTabs.setTabsClosable(False)
        self.assetsTabs.setMovable(False)
        self.assetsTabs.setTabBarAutoHide(False)
        self.demoList = QWidget()
        self.demoList.setObjectName(u"demoList")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.demoList.sizePolicy().hasHeightForWidth())
        self.demoList.setSizePolicy(sizePolicy1)
        self.verticalLayout_11 = QVBoxLayout(self.demoList)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_12 = QVBoxLayout()
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.browseDemoBtn = QPushButton(self.demoList)
        self.browseDemoBtn.setObjectName(u"browseDemoBtn")

        self.horizontalLayout_10.addWidget(self.browseDemoBtn)

        self.browseScriptBtn = QPushButton(self.demoList)
        self.browseScriptBtn.setObjectName(u"browseScriptBtn")

        self.horizontalLayout_10.addWidget(self.browseScriptBtn)

        self.browseAudioBtn = QPushButton(self.demoList)
        self.browseAudioBtn.setObjectName(u"browseAudioBtn")

        self.horizontalLayout_10.addWidget(self.browseAudioBtn)


        self.verticalLayout_12.addLayout(self.horizontalLayout_10)


        self.verticalLayout_11.addLayout(self.verticalLayout_12)

        self.demoListTreeWidget = QTreeWidget(self.demoList)
        self.demoListTreeWidget.setObjectName(u"demoListTreeWidget")

        self.verticalLayout_11.addWidget(self.demoListTreeWidget)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.infoBtn = QPushButton(self.demoList)
        self.infoBtn.setObjectName(u"infoBtn")

        self.horizontalLayout_11.addWidget(self.infoBtn)

        self.loadScriptBtn = QPushButton(self.demoList)
        self.loadScriptBtn.setObjectName(u"loadScriptBtn")

        self.horizontalLayout_11.addWidget(self.loadScriptBtn)

        self.loadAudioBtn = QPushButton(self.demoList)
        self.loadAudioBtn.setObjectName(u"loadAudioBtn")

        self.horizontalLayout_11.addWidget(self.loadAudioBtn)

        self.removeDemoBtn = QPushButton(self.demoList)
        self.removeDemoBtn.setObjectName(u"removeDemoBtn")

        self.horizontalLayout_11.addWidget(self.removeDemoBtn)

        self.addDemoBtn = QPushButton(self.demoList)
        self.addDemoBtn.setObjectName(u"addDemoBtn")

        self.horizontalLayout_11.addWidget(self.addDemoBtn)


        self.verticalLayout_11.addLayout(self.horizontalLayout_11)

        self.assetsTabs.addTab(self.demoList, "")
        self.scriptOverviewTab = QWidget()
        self.scriptOverviewTab.setObjectName(u"scriptOverviewTab")
        self.verticalLayout_13 = QVBoxLayout(self.scriptOverviewTab)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.scriptListTreeWidget = QListWidget(self.scriptOverviewTab)
        self.scriptListTreeWidget.setObjectName(u"scriptListTreeWidget")

        self.verticalLayout_13.addWidget(self.scriptListTreeWidget)

        self.assetsTabs.addTab(self.scriptOverviewTab, "")
        self.audioOverviewTab = QWidget()
        self.audioOverviewTab.setObjectName(u"audioOverviewTab")
        self.verticalLayout_15 = QVBoxLayout(self.audioOverviewTab)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.audioListTreeWidget = QListWidget(self.audioOverviewTab)
        self.audioListTreeWidget.setObjectName(u"audioListTreeWidget")

        self.verticalLayout_15.addWidget(self.audioListTreeWidget)

        self.assetsTabs.addTab(self.audioOverviewTab, "")

        self.stepsLayout.addWidget(self.assetsTabs)

        self.opsTabs = QTabWidget(self.centralTabsPage1_2)
        self.opsTabs.setObjectName(u"opsTabs")
        self.opsTabs.setEnabled(True)
        self.opsTabs.setMaximumSize(QSize(410, 16777215))
        self.stepsTab = QWidget()
        self.stepsTab.setObjectName(u"stepsTab")
        sizePolicy1.setHeightForWidth(self.stepsTab.sizePolicy().hasHeightForWidth())
        self.stepsTab.setSizePolicy(sizePolicy1)
        self.stepsTab.setMinimumSize(QSize(200, 278))
        self.stepsTab.setAutoFillBackground(False)
        self.verticalLayout_2 = QVBoxLayout(self.stepsTab)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(-1, 11, -1, -1)
        self.stepsTreeWidget = QTreeWidget(self.stepsTab)
        self.stepsTreeWidget.setObjectName(u"stepsTreeWidget")

        self.verticalLayout_2.addWidget(self.stepsTreeWidget)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.stepDownBtn = QPushButton(self.stepsTab)
        self.stepDownBtn.setObjectName(u"stepDownBtn")

        self.horizontalLayout_3.addWidget(self.stepDownBtn)

        self.stepUpBtn = QPushButton(self.stepsTab)
        self.stepUpBtn.setObjectName(u"stepUpBtn")

        self.horizontalLayout_3.addWidget(self.stepUpBtn)

        self.removeStepBtn = QPushButton(self.stepsTab)
        self.removeStepBtn.setObjectName(u"removeStepBtn")

        self.horizontalLayout_3.addWidget(self.removeStepBtn)

        self.addStepBtn = QPushButton(self.stepsTab)
        self.addStepBtn.setObjectName(u"addStepBtn")

        self.horizontalLayout_3.addWidget(self.addStepBtn)

        self.runBtn = QPushButton(self.stepsTab)
        self.runBtn.setObjectName(u"runBtn")
        sizePolicy2 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.runBtn.sizePolicy().hasHeightForWidth())
        self.runBtn.setSizePolicy(sizePolicy2)
        self.runBtn.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setBold(False)
        self.runBtn.setFont(font)
        self.runBtn.setCheckable(False)
        self.runBtn.setFlat(False)

        self.horizontalLayout_3.addWidget(self.runBtn)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.opsTabs.addTab(self.stepsTab, "")
        self.optionsTab = QWidget()
        self.optionsTab.setObjectName(u"optionsTab")
        self.optionsTab.setAutoFillBackground(True)
        self.verticalLayout_17 = QVBoxLayout(self.optionsTab)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.stepOptionsTreeWidget = QTreeWidget(self.optionsTab)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.stepOptionsTreeWidget.setHeaderItem(__qtreewidgetitem)
        self.stepOptionsTreeWidget.setObjectName(u"stepOptionsTreeWidget")

        self.verticalLayout_17.addWidget(self.stepOptionsTreeWidget)

        self.opsTabs.addTab(self.optionsTab, "")
        self.templatesTab = QWidget()
        self.templatesTab.setObjectName(u"templatesTab")
        self.verticalLayout_19 = QVBoxLayout(self.templatesTab)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.treeWidget = QTreeWidget(self.templatesTab)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem1)
        self.treeWidget.setObjectName(u"treeWidget")

        self.verticalLayout_19.addWidget(self.treeWidget)

        self.opsTabs.addTab(self.templatesTab, "")

        self.stepsLayout.addWidget(self.opsTabs)


        self.horizontalLayout_2.addLayout(self.stepsLayout)

        self.stepTabs = QTabWidget(self.centralTabsPage1_2)
        self.stepTabs.setObjectName(u"stepTabs")
        self.stepTabs.setDocumentMode(False)
        self.stepTabs.setTabsClosable(True)
        self.stepTabs.setMovable(True)
        self.stepTabs.setTabBarAutoHide(False)

        self.horizontalLayout_2.addWidget(self.stepTabs)

        self.demoLayout = QVBoxLayout()
        self.demoLayout.setObjectName(u"demoLayout")
        self.objectViewTabW = QStackedWidget(self.centralTabsPage1_2)
        self.objectViewTabW.setObjectName(u"objectViewTabW")
        self.objectViewTabWPage1 = QWidget()
        self.objectViewTabWPage1.setObjectName(u"objectViewTabWPage1")
        self.verticalLayout_9 = QVBoxLayout(self.objectViewTabWPage1)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.demoTreeBox = QGroupBox(self.objectViewTabWPage1)
        self.demoTreeBox.setObjectName(u"demoTreeBox")
        self.demoTreeBox.setFlat(True)
        self.verticalLayout_6 = QVBoxLayout(self.demoTreeBox)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.demoTreeWidget = QTreeWidget(self.demoTreeBox)
        __qtreewidgetitem2 = QTreeWidgetItem()
        __qtreewidgetitem2.setText(0, u"Step");
        self.demoTreeWidget.setHeaderItem(__qtreewidgetitem2)
        self.demoTreeWidget.setObjectName(u"demoTreeWidget")

        self.verticalLayout_6.addWidget(self.demoTreeWidget)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.demoDuplicateBtn = QPushButton(self.demoTreeBox)
        self.demoDuplicateBtn.setObjectName(u"demoDuplicateBtn")

        self.horizontalLayout_5.addWidget(self.demoDuplicateBtn)

        self.demoInsertSectionBtn = QPushButton(self.demoTreeBox)
        self.demoInsertSectionBtn.setObjectName(u"demoInsertSectionBtn")

        self.horizontalLayout_5.addWidget(self.demoInsertSectionBtn)

        self.demoDeleteBtn = QPushButton(self.demoTreeBox)
        self.demoDeleteBtn.setObjectName(u"demoDeleteBtn")

        self.horizontalLayout_5.addWidget(self.demoDeleteBtn)

        self.demoAddStepBtn = QPushButton(self.demoTreeBox)
        self.demoAddStepBtn.setObjectName(u"demoAddStepBtn")

        self.horizontalLayout_5.addWidget(self.demoAddStepBtn)

        self.demoOverflowBtn = QToolButton(self.demoTreeBox)
        self.demoOverflowBtn.setObjectName(u"demoOverflowBtn")

        self.horizontalLayout_5.addWidget(self.demoOverflowBtn)


        self.verticalLayout_6.addLayout(self.horizontalLayout_5)


        self.verticalLayout_9.addWidget(self.demoTreeBox)

        self.dataFrame = QGroupBox(self.objectViewTabWPage1)
        self.dataFrame.setObjectName(u"dataFrame")
        self.dataFrame.setMaximumSize(QSize(16777215, 300))
        self.dataFrame.setFlat(True)
        self.verticalLayout_8 = QVBoxLayout(self.dataFrame)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.dataStack = QStackedWidget(self.dataFrame)
        self.dataStack.setObjectName(u"dataStack")
        self.stepDataL = QWidget()
        self.stepDataL.setObjectName(u"stepDataL")
        self.verticalLayout_14 = QVBoxLayout(self.stepDataL)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.metadataTreeWidget = QTreeWidget(self.stepDataL)
        self.metadataTreeWidget.setObjectName(u"metadataTreeWidget")

        self.verticalLayout_14.addWidget(self.metadataTreeWidget)

        self.stepDataBtnL = QHBoxLayout()
        self.stepDataBtnL.setObjectName(u"stepDataBtnL")
        self.pushButton_2 = QPushButton(self.stepDataL)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.stepDataBtnL.addWidget(self.pushButton_2)

        self.pushButton = QPushButton(self.stepDataL)
        self.pushButton.setObjectName(u"pushButton")

        self.stepDataBtnL.addWidget(self.pushButton)

        self.toolButton = QToolButton(self.stepDataL)
        self.toolButton.setObjectName(u"toolButton")

        self.stepDataBtnL.addWidget(self.toolButton)


        self.verticalLayout_14.addLayout(self.stepDataBtnL)

        self.dataStack.addWidget(self.stepDataL)
        self.sectDataL = QWidget()
        self.sectDataL.setObjectName(u"sectDataL")
        self.verticalLayout_16 = QVBoxLayout(self.sectDataL)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.sectionDataTreeW = QTreeWidget(self.sectDataL)
        self.sectionDataTreeW.setObjectName(u"sectionDataTreeW")

        self.verticalLayout_16.addWidget(self.sectionDataTreeW)

        self.sectionDataBtnL = QHBoxLayout()
        self.sectionDataBtnL.setObjectName(u"sectionDataBtnL")
        self.pushButton_4 = QPushButton(self.sectDataL)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.sectionDataBtnL.addWidget(self.pushButton_4)

        self.pushButton_3 = QPushButton(self.sectDataL)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.sectionDataBtnL.addWidget(self.pushButton_3)

        self.pushButton_5 = QPushButton(self.sectDataL)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.sectionDataBtnL.addWidget(self.pushButton_5)

        self.toolButton_2 = QToolButton(self.sectDataL)
        self.toolButton_2.setObjectName(u"toolButton_2")

        self.sectionDataBtnL.addWidget(self.toolButton_2)


        self.verticalLayout_16.addLayout(self.sectionDataBtnL)

        self.dataStack.addWidget(self.sectDataL)

        self.verticalLayout_8.addWidget(self.dataStack)


        self.verticalLayout_9.addWidget(self.dataFrame)

        self.objectViewTabW.addWidget(self.objectViewTabWPage1)
        self.objectViewTabWPage2 = QWidget()
        self.objectViewTabWPage2.setObjectName(u"objectViewTabWPage2")
        self.objectViewTabW.addWidget(self.objectViewTabWPage2)
        self.objectViewTabWPage3 = QWidget()
        self.objectViewTabWPage3.setObjectName(u"objectViewTabWPage3")
        self.objectViewTabW.addWidget(self.objectViewTabWPage3)
        self.objectViewTabWPage4 = QWidget()
        self.objectViewTabWPage4.setObjectName(u"objectViewTabWPage4")
        self.objectViewTabW.addWidget(self.objectViewTabWPage4)

        self.demoLayout.addWidget(self.objectViewTabW)


        self.horizontalLayout_2.addLayout(self.demoLayout)

        self.centralTabs.addTab(self.centralTabsPage1_2, "")
        self.centralTabsPage2_2 = QWidget()
        self.centralTabsPage2_2.setObjectName(u"centralTabsPage2_2")
        self.centralTabs.addTab(self.centralTabsPage2_2, "")
        self.centralTabsPage3 = QWidget()
        self.centralTabsPage3.setObjectName(u"centralTabsPage3")
        self.centralTabs.addTab(self.centralTabsPage3, "")

        self.verticalLayout_10.addWidget(self.centralTabs)

        IscApp.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(IscApp)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1440, 21))
        self.menubar.setDefaultUp(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExport_2 = QMenu(self.menuFile)
        self.menuExport_2.setObjectName(u"menuExport_2")
        self.menuNew = QMenu(self.menuFile)
        self.menuNew.setObjectName(u"menuNew")
        self.menuOpen = QMenu(self.menuFile)
        self.menuOpen.setObjectName(u"menuOpen")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSelect_all = QMenu(self.menuEdit)
        self.menuSelect_all.setObjectName(u"menuSelect_all")
        self.menuSelect_associated = QMenu(self.menuEdit)
        self.menuSelect_associated.setObjectName(u"menuSelect_associated")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuView.setTearOffEnabled(False)
        self.menuView.setToolTipsVisible(True)
        self.menuZoom = QMenu(self.menuView)
        self.menuZoom.setObjectName(u"menuZoom")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuAudio = QMenu(self.menuTools)
        self.menuAudio.setObjectName(u"menuAudio")
        self.menuImage = QMenu(self.menuTools)
        self.menuImage.setObjectName(u"menuImage")
        self.menuInsert = QMenu(self.menuImage)
        self.menuInsert.setObjectName(u"menuInsert")
        self.menuShell = QMenu(self.menuImage)
        self.menuShell.setObjectName(u"menuShell")
        self.menuDemo = QMenu(self.menuTools)
        self.menuDemo.setObjectName(u"menuDemo")
        self.menuScript = QMenu(self.menuTools)
        self.menuScript.setObjectName(u"menuScript")
        self.menuCheck_script_for = QMenu(self.menuScript)
        self.menuCheck_script_for.setObjectName(u"menuCheck_script_for")
        self.menuClear = QMenu(self.menuScript)
        self.menuClear.setObjectName(u"menuClear")
        self.menuWeb = QMenu(self.menuTools)
        self.menuWeb.setObjectName(u"menuWeb")
        self.menuSection = QMenu(self.menuTools)
        self.menuSection.setObjectName(u"menuSection")
        self.menuPacing = QMenu(self.menuSection)
        self.menuPacing.setObjectName(u"menuPacing")
        self.menuAudio_2 = QMenu(self.menuSection)
        self.menuAudio_2.setObjectName(u"menuAudio_2")
        self.menuStep = QMenu(self.menuTools)
        self.menuStep.setObjectName(u"menuStep")
        self.menuAudio_3 = QMenu(self.menuStep)
        self.menuAudio_3.setObjectName(u"menuAudio_3")
        self.menuPacing_2 = QMenu(self.menuStep)
        self.menuPacing_2.setObjectName(u"menuPacing_2")
        self.menuImage_2 = QMenu(self.menuStep)
        self.menuImage_2.setObjectName(u"menuImage_2")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuHow_do_I = QMenu(self.menuHelp)
        self.menuHow_do_I.setObjectName(u"menuHow_do_I")
        IscApp.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(IscApp)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setMinimumSize(QSize(0, 30))
        self.statusbar.setSizeGripEnabled(False)
        IscApp.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.menuExport_2.menuAction())
        self.menuExport_2.addAction(self.actionDemo)
        self.menuExport_2.addAction(self.actionAudio)
        self.menuExport_2.addAction(self.actionScript)
        self.menuNew.addAction(self.actionNewStep)
        self.menuOpen.addAction(self.actionOpenDemo)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuSelect_all.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuSelect_associated.menuAction())
        self.menuSelect_all.addAction(self.actionSections)
        self.menuSelect_all.addAction(self.actionsteps)
        self.menuSelect_associated.addAction(self.actionSection)
        self.menuSelect_associated.addAction(self.actionSteps_in_section)
        self.menuSelect_associated.addAction(self.actionFirst_step_in_section)
        self.menuView.addAction(self.actionView_statusbar)
        self.menuView.addAction(self.actionView_step_preview)
        self.menuView.addAction(self.actionView_demo_in_folder)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menuView.addAction(self.actionView_menubar)
        self.menuView.addAction(self.actionView_in_file_explorer)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionView_menubar_2)
        self.menuZoom.addAction(self.actionZoom_in)
        self.menuZoom.addAction(self.actionZoom_out)
        self.menuZoom.addAction(self.actionReset_zoom)
        self.menuTools.addAction(self.menuAudio.menuAction())
        self.menuTools.addAction(self.menuImage.menuAction())
        self.menuTools.addAction(self.menuDemo.menuAction())
        self.menuTools.addAction(self.menuScript.menuAction())
        self.menuTools.addAction(self.menuWeb.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuSection.menuAction())
        self.menuTools.addAction(self.menuStep.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPreferences)
        self.menuAudio.addAction(self.actionAttach_audio_to_demo_2)
        self.menuAudio.addAction(self.actionBulk_edit_demo_audio)
        self.menuAudio.addAction(self.actionEdit_step_audio)
        self.menuImage.addAction(self.actionBulk_paste_image)
        self.menuImage.addAction(self.actionBulk_image_paste_wizard)
        self.menuImage.addAction(self.actionBulk_shell_demo_assets)
        self.menuImage.addAction(self.menuInsert.menuAction())
        self.menuImage.addAction(self.menuShell.menuAction())
        self.menuImage.addAction(self.actionCrop)
        self.menuImage.addAction(self.actionResize)
        self.menuImage.addAction(self.actionCapture_image_edt_macro)
        self.menuInsert.addAction(self.actionSingle_image)
        self.menuInsert.addAction(self.actionMultiple_images)
        self.menuInsert.addAction(self.actionImage_insert_wizar)
        self.menuShell.addAction(self.actionAdd_background_image)
        self.menuShell.addAction(self.actionAdd_background_and_wrapper)
        self.menuShell.addAction(self.actionShell_wizard)
        self.menuDemo.addAction(self.actionSection_demo)
        self.menuDemo.addAction(self.actionPacing_wizard)
        self.menuDemo.addAction(self.actionCompose_demos)
        self.menuDemo.addAction(self.actionBulk_edit_demo_metadata)
        self.menuDemo.addAction(self.actionPackage_demo)
        self.menuDemo.addAction(self.actionAdd_scroll_section)
        self.menuDemo.addAction(self.actionAdd_step)
        self.menuDemo.addAction(self.actionEdit_XML)
        self.menuScript.addAction(self.actionLoad_script)
        self.menuScript.addAction(self.actionConvert_script)
        self.menuScript.addAction(self.menuCheck_script_for.menuAction())
        self.menuScript.addAction(self.menuClear.menuAction())
        self.menuCheck_script_for.addAction(self.actionSpelling_errors)
        self.menuCheck_script_for.addAction(self.actionGrammar_errors)
        self.menuCheck_script_for.addAction(self.actionProduction_notes)
        self.menuClear.addAction(self.actionTalking_points)
        self.menuClear.addAction(self.actionClick_instructions)
        self.menuWeb.addAction(self.actionUpload_to_CloudGuides)
        self.menuSection.addAction(self.actionSet_section_as_animated)
        self.menuSection.addAction(self.actionSet_section_as_guided)
        self.menuSection.addAction(self.actionMove_2)
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.actionSet_as_animated)
        self.menuSection.addAction(self.actionSet_as_guided)
        self.menuSection.addAction(self.actionSet_as_scroll)
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.menuAudio_2.menuAction())
        self.menuSection.addAction(self.menuPacing.menuAction())
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.actionView_metadata)
        self.menuPacing.addAction(self.actionDecrement_step_delay)
        self.menuPacing.addAction(self.actionIncrement_step_delay)
        self.menuAudio_2.addAction(self.actionAdd_audio_2)
        self.menuAudio_2.addAction(self.actionDelete_audio)
        self.menuAudio_2.addAction(self.actionEdit_audio_2)
        self.menuAudio_2.addAction(self.actionReplace_audio)
        self.menuStep.addAction(self.actionDelete)
        self.menuStep.addAction(self.actionDuplicate)
        self.menuStep.addAction(self.actionDuplicate_as_pacing)
        self.menuStep.addAction(self.actionMove)
        self.menuStep.addSeparator()
        self.menuStep.addAction(self.menuAudio_3.menuAction())
        self.menuStep.addAction(self.menuPacing_2.menuAction())
        self.menuStep.addAction(self.menuImage_2.menuAction())
        self.menuStep.addSeparator()
        self.menuStep.addAction(self.actionAdd_text_box)
        self.menuStep.addAction(self.actionAdd_highlight)
        self.menuStep.addAction(self.actionAdd_jump_box)
        self.menuStep.addSeparator()
        self.menuStep.addAction(self.actionSet_animated)
        self.menuStep.addAction(self.actionSet_guided)
        self.menuStep.addAction(self.actionFrom_capture)
        self.menuAudio_3.addAction(self.actionAdd_audio_3)
        self.menuAudio_3.addAction(self.actionDelete_audio_2)
        self.menuAudio_3.addAction(self.actionReplace_audio_2)
        self.menuAudio_3.addAction(self.actionEdit_audio_3)
        self.menuPacing_2.addAction(self.actionIncrement_step_delay_2)
        self.menuPacing_2.addAction(self.actionDecrement_step_delay_2)
        self.menuImage_2.addAction(self.actionPreview)
        self.menuImage_2.addAction(self.actionView_in_folder)
        self.menuImage_2.addAction(self.actionEdit)
        self.menuImage_2.addAction(self.actionReplace_image)
        self.menuWindow.addAction(self.actionOpen_DemoMate)
        self.menuWindow.addAction(self.actionOpen_Cloudguides_Packaging)
        self.menuWindow.addAction(self.actionClose)
        self.menuWindow.addAction(self.actionOpen_assets_folder)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.menuHow_do_I.menuAction())
        self.menuHelp.addSeparator()
        self.menuHow_do_I.addAction(self.actionBulk_insert_image)
        self.menuHow_do_I.addAction(self.actionBulk_shell_steps)
        self.menuHow_do_I.addAction(self.actionBulk_crop_step_assets)
        self.menuHow_do_I.addAction(self.actionAttach_audio_to_demo)

        self.retranslateUi(IscApp)
        self.actionOpenDemo.triggered.connect(self.browseDemoBtn.click)

        self.centralTabs.setCurrentIndex(0)
        self.assetsTabs.setCurrentIndex(1)
        self.opsTabs.setCurrentIndex(0)
        self.dataStack.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(IscApp)
    # setupUi

    def retranslateUi(self, IscApp):
        IscApp.setWindowTitle(QCoreApplication.translate("IscApp", u"IscApp", None))
        self.actionUndo.setText(QCoreApplication.translate("IscApp", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("IscApp", u"Redo", None))
        self.actionView_statusbar.setText(QCoreApplication.translate("IscApp", u"View statusbar", None))
        self.actionView_step_preview.setText(QCoreApplication.translate("IscApp", u"View step preview", None))
        self.actionInsert.setText(QCoreApplication.translate("IscApp", u"Insert Image", None))
        self.actionShell_Image.setText(QCoreApplication.translate("IscApp", u"Shell Image", None))
        self.actionSection_steps.setText(QCoreApplication.translate("IscApp", u"Section steps", None))
        self.actionAttach_audio.setText(QCoreApplication.translate("IscApp", u"Attach audio", None))
        self.actionBulk_crop.setText(QCoreApplication.translate("IscApp", u"Bulk crop", None))
        self.actionView_demo_in_folder.setText(QCoreApplication.translate("IscApp", u"View demo in folder", None))
        self.actionLoad_tool_state.setText(QCoreApplication.translate("IscApp", u"Load tool state", None))
        self.actionSave_tool_state.setText(QCoreApplication.translate("IscApp", u"Save tool state", None))
        self.actionOpen_DemoMate.setText(QCoreApplication.translate("IscApp", u"Open Demo in DemoMate", None))
        self.actionOpen_Cloudguides_Packaging.setText(QCoreApplication.translate("IscApp", u"Open Cloudguides Packaging tool", None))
        self.actionAbout.setText(QCoreApplication.translate("IscApp", u"About", None))
        self.actionHelp_2.setText(QCoreApplication.translate("IscApp", u"Help", None))
        self.actionImage_Insert.setText(QCoreApplication.translate("IscApp", u"Insert image", None))
        self.actionImage_Shelling.setText(QCoreApplication.translate("IscApp", u"Shell image", None))
        self.actionHelp_3.setText(QCoreApplication.translate("IscApp", u"Help", None))
        self.actionBulk_insert_image.setText(QCoreApplication.translate("IscApp", u"Bulk insert image into step assets", None))
        self.actionBulk_shell_steps.setText(QCoreApplication.translate("IscApp", u"Bulk shell step assets", None))
        self.actionBulk_crop_step_assets.setText(QCoreApplication.translate("IscApp", u"Bulk crop step assets", None))
        self.actionAttach_audio_to_demo.setText(QCoreApplication.translate("IscApp", u"Attach audio to demo", None))
        self.actionClose.setText(QCoreApplication.translate("IscApp", u"Open folder containing demo", None))
        self.actionClose_2.setText(QCoreApplication.translate("IscApp", u"Close", None))
        self.actionFrom_demo_file.setText(QCoreApplication.translate("IscApp", u"From .demo file", None))
        self.actionFrom_exe_installer.setText(QCoreApplication.translate("IscApp", u"From .exe installer", None))
        self.actionFrom_docx_file.setText(QCoreApplication.translate("IscApp", u"From .docx file", None))
        self.actionFrom_scripts_folder.setText(QCoreApplication.translate("IscApp", u"From scripts folder", None))
        self.actionOverwrite.setText(QCoreApplication.translate("IscApp", u"Overwrite", None))
        self.actionMerge_demos.setText(QCoreApplication.translate("IscApp", u"Merge demos", None))
        self.actionLoad_audio_directory.setText(QCoreApplication.translate("IscApp", u"Load Audio", None))
        self.actionLoad_soundbite.setText(QCoreApplication.translate("IscApp", u"Load from .zip", None))
        self.actionEdit_audio.setText(QCoreApplication.translate("IscApp", u"Edit audio", None))
        self.actionAttach_audio_to_demo_2.setText(QCoreApplication.translate("IscApp", u"Attach audio to demo", None))
        self.actionBulk_edit_demo_audio.setText(QCoreApplication.translate("IscApp", u"Bulk edit demo audio", None))
        self.actionEdit_step_audio.setText(QCoreApplication.translate("IscApp", u"Edit step audio", None))
        self.actionBulk_paste_image.setText(QCoreApplication.translate("IscApp", u"Bulk paste image", None))
        self.actionBulk_image_paste_wizard.setText(QCoreApplication.translate("IscApp", u"Bulk image paste wizard", None))
        self.actionBulk_shell_demo_assets.setText(QCoreApplication.translate("IscApp", u"Bulk shell demo assets", None))
        self.actionSection_demo.setText(QCoreApplication.translate("IscApp", u"Section demo", None))
        self.actionBulk_resize_demo_assets.setText(QCoreApplication.translate("IscApp", u"Bulk resize demo assets", None))
        self.actionBulk_crop_demo_assets.setText(QCoreApplication.translate("IscApp", u"Bulk crop demo assets", None))
        self.actionPacing_wizard.setText(QCoreApplication.translate("IscApp", u"Open pacing wizard", None))
        self.actionCompose_demos.setText(QCoreApplication.translate("IscApp", u"Compose demos", None))
        self.actionBulk_edit_demo_metadata.setText(QCoreApplication.translate("IscApp", u"View/edit metadata", None))
        self.actionLoad_script.setText(QCoreApplication.translate("IscApp", u"Load Script", None))
#if QT_CONFIG(shortcut)
        self.actionLoad_script.setShortcut(QCoreApplication.translate("IscApp", u"Alt+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionConvert_script.setText(QCoreApplication.translate("IscApp", u"Convert script", None))
        self.actionSpelling_errors.setText(QCoreApplication.translate("IscApp", u"Spelling errors", None))
        self.actionGrammar_errors.setText(QCoreApplication.translate("IscApp", u"Grammar errors", None))
        self.actionProduction_notes.setText(QCoreApplication.translate("IscApp", u"Production notes", None))
        self.actionTalking_points.setText(QCoreApplication.translate("IscApp", u"Talking points", None))
        self.actionClick_instructions.setText(QCoreApplication.translate("IscApp", u"Click instructions", None))
        self.actionPackage_demo.setText(QCoreApplication.translate("IscApp", u"Package demo", None))
        self.actionSingle_image.setText(QCoreApplication.translate("IscApp", u"Single image", None))
        self.actionMultiple_images.setText(QCoreApplication.translate("IscApp", u"Multiple images", None))
        self.actionImage_insert_wizar.setText(QCoreApplication.translate("IscApp", u"From asset region", None))
        self.actionAdd_background_image.setText(QCoreApplication.translate("IscApp", u"Add background image", None))
        self.actionAdd_background_and_wrapper.setText(QCoreApplication.translate("IscApp", u"Add background and wrapper", None))
        self.actionShell_wizard.setText(QCoreApplication.translate("IscApp", u"Shell wizard", None))
        self.actionCrop.setText(QCoreApplication.translate("IscApp", u"Crop", None))
        self.actionResize.setText(QCoreApplication.translate("IscApp", u"Resize", None))
        self.actionLoad_operation.setText(QCoreApplication.translate("IscApp", u"Add operation...", None))
        self.actionSave_operation.setText(QCoreApplication.translate("IscApp", u"Load operation...", None))
        self.actionClose_3.setText(QCoreApplication.translate("IscApp", u"Save operation...", None))
        self.actionZoom_in.setText(QCoreApplication.translate("IscApp", u"Zoom in", None))
        self.actionAdd_scroll_section.setText(QCoreApplication.translate("IscApp", u"Add scroll section", None))
        self.actionOpen_assets_folder.setText(QCoreApplication.translate("IscApp", u"Open assets folder", None))
        self.actionUpload_to_CloudGuides.setText(QCoreApplication.translate("IscApp", u"Upload to CloudGuides", None))
        self.actionSections.setText(QCoreApplication.translate("IscApp", u"Sections", None))
        self.actionsteps.setText(QCoreApplication.translate("IscApp", u"Steps", None))
        self.actionSection.setText(QCoreApplication.translate("IscApp", u"Section", None))
        self.actionSteps_in_section.setText(QCoreApplication.translate("IscApp", u"Steps in section", None))
        self.actionFirst_step_in_section.setText(QCoreApplication.translate("IscApp", u"First step in section", None))
        self.actionSet_section_as_animated.setText(QCoreApplication.translate("IscApp", u"Delete", None))
        self.actionSet_section_as_guided.setText(QCoreApplication.translate("IscApp", u"Duplicate", None))
        self.actionDelete.setText(QCoreApplication.translate("IscApp", u"Delete", None))
        self.actionDuplicate.setText(QCoreApplication.translate("IscApp", u"Duplicate", None))
        self.actionDuplicate_as_pacing.setText(QCoreApplication.translate("IscApp", u"Duplicate as pacing", None))
        self.actionMove.setText(QCoreApplication.translate("IscApp", u"Move", None))
        self.actionMove_2.setText(QCoreApplication.translate("IscApp", u"Move", None))
        self.actionSet_as_animated.setText(QCoreApplication.translate("IscApp", u"Set as animated", None))
        self.actionSet_as_guided.setText(QCoreApplication.translate("IscApp", u"Set as guided", None))
        self.actionSet_as_scroll.setText(QCoreApplication.translate("IscApp", u"Set as scroll", None))
        self.actionDecrement_step_delay.setText(QCoreApplication.translate("IscApp", u"Decrement step delay", None))
        self.actionIncrement_step_delay.setText(QCoreApplication.translate("IscApp", u"Increment step delay", None))
        self.actionAdd_audio_2.setText(QCoreApplication.translate("IscApp", u"Add audio", None))
        self.actionDelete_audio.setText(QCoreApplication.translate("IscApp", u"Delete audio", None))
        self.actionEdit_audio_2.setText(QCoreApplication.translate("IscApp", u"Edit audio", None))
        self.actionReplace_audio.setText(QCoreApplication.translate("IscApp", u"Replace audio", None))
        self.actionView_metadata.setText(QCoreApplication.translate("IscApp", u"View metadata", None))
        self.actionAdd_audio_3.setText(QCoreApplication.translate("IscApp", u"Add audio", None))
        self.actionDelete_audio_2.setText(QCoreApplication.translate("IscApp", u"Delete audio", None))
        self.actionReplace_audio_2.setText(QCoreApplication.translate("IscApp", u"Replace audio", None))
        self.actionEdit_audio_3.setText(QCoreApplication.translate("IscApp", u"Edit audio", None))
        self.actionIncrement_step_delay_2.setText(QCoreApplication.translate("IscApp", u"Increment step delay", None))
        self.actionDecrement_step_delay_2.setText(QCoreApplication.translate("IscApp", u"Decrement step delay", None))
        self.actionPreview.setText(QCoreApplication.translate("IscApp", u"Preview image", None))
        self.actionView_in_folder.setText(QCoreApplication.translate("IscApp", u"View in folder", None))
        self.actionEdit.setText(QCoreApplication.translate("IscApp", u"Edit image", None))
        self.actionReplace_image.setText(QCoreApplication.translate("IscApp", u"Replace image", None))
        self.actionView_metadata_2.setText(QCoreApplication.translate("IscApp", u"View metadata", None))
        self.actionLoad_SoundBite.setText(QCoreApplication.translate("IscApp", u"Load soundbite", None))
        self.actionFrom_recording.setText(QCoreApplication.translate("IscApp", u"From recording", None))
        self.actionAs_new_version.setText(QCoreApplication.translate("IscApp", u"As new version", None))
        self.actionAs_new_round.setText(QCoreApplication.translate("IscApp", u"As new round", None))
        self.actionExport_to_installer.setText(QCoreApplication.translate("IscApp", u"Export to installer", None))
        self.actionExport_to_Cloudguide.setText(QCoreApplication.translate("IscApp", u"Export to Cloudguide", None))
        self.actionTo_installer.setText(QCoreApplication.translate("IscApp", u"To installer", None))
        self.actionTo_Cloudguide.setText(QCoreApplication.translate("IscApp", u"To Cloudguide", None))
        self.actionOverwrite_2.setText(QCoreApplication.translate("IscApp", u"Overwrite", None))
        self.actionAs_new_version_2.setText(QCoreApplication.translate("IscApp", u"As new version", None))
        self.actionAs_new_round_2.setText(QCoreApplication.translate("IscApp", u"As new round", None))
        self.actionAs_txt.setText(QCoreApplication.translate("IscApp", u"As .txt", None))
        self.actionTo_new_directory.setText(QCoreApplication.translate("IscApp", u"To new directory", None))
        self.actionOverwrite_3.setText(QCoreApplication.translate("IscApp", u"Overwrite", None))
        self.actionClose_window.setText(QCoreApplication.translate("IscApp", u"Close window", None))
        self.actionReset_demo.setText(QCoreApplication.translate("IscApp", u"Reset demo", None))
        self.actionNew.setText(QCoreApplication.translate("IscApp", u"New...", None))
        self.actionNew_operation.setText(QCoreApplication.translate("IscApp", u"New operation...", None))
        self.actionAdd_step.setText(QCoreApplication.translate("IscApp", u"Add step", None))
        self.actionPreferences.setText(QCoreApplication.translate("IscApp", u"Preferences", None))
        self.actionAdd_text_box.setText(QCoreApplication.translate("IscApp", u"Add text box", None))
        self.actionAdd_highlight.setText(QCoreApplication.translate("IscApp", u"Add highlight", None))
        self.actionAdd_jump_box.setText(QCoreApplication.translate("IscApp", u"Add jump box", None))
        self.actionSet_animated.setText(QCoreApplication.translate("IscApp", u"Set animated", None))
        self.actionSet_guided.setText(QCoreApplication.translate("IscApp", u"Set guided", None))
        self.actionEdit_XML.setText(QCoreApplication.translate("IscApp", u"Edit XML", None))
        self.actionFrom_capture.setText(QCoreApplication.translate("IscApp", u"From capture", None))
        self.actionCapture_image_edt_macro.setText(QCoreApplication.translate("IscApp", u"Capture image edt macro", None))
        self.actionNew_tab.setText(QCoreApplication.translate("IscApp", u"New tab", None))
        self.actionNew_2.setText(QCoreApplication.translate("IscApp", u"New...", None))
        self.actionTo_new_version.setText(QCoreApplication.translate("IscApp", u"To new version", None))
        self.actionTo_new_round.setText(QCoreApplication.translate("IscApp", u"To new round", None))
        self.actionSteps.setText(QCoreApplication.translate("IscApp", u"Steps...", None))
        self.actionOverwrite_existing.setText(QCoreApplication.translate("IscApp", u"Overwrite existing", None))
        self.actionSave.setText(QCoreApplication.translate("IscApp", u"Save...", None))
        self.actionDemo.setText(QCoreApplication.translate("IscApp", u"Demo...", None))
        self.actionAudio.setText(QCoreApplication.translate("IscApp", u"Audio...", None))
        self.actionScript.setText(QCoreApplication.translate("IscApp", u"Script..", None))
        self.actionView_menubar.setText(QCoreApplication.translate("IscApp", u"View console", None))
        self.actionView_in_file_explorer.setText(QCoreApplication.translate("IscApp", u"View in file explorer", None))
#if QT_CONFIG(shortcut)
        self.actionView_in_file_explorer.setShortcut(QCoreApplication.translate("IscApp", u"Ctrl+Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionView_menubar_2.setText(QCoreApplication.translate("IscApp", u"View menubar", None))
#if QT_CONFIG(shortcut)
        self.actionView_menubar_2.setShortcut(QCoreApplication.translate("IscApp", u"Alt+M", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoom_out.setText(QCoreApplication.translate("IscApp", u"Zoom out", None))
        self.actionReset_zoom.setText(QCoreApplication.translate("IscApp", u"Reset zoom", None))
        self.actionNewStep.setText(QCoreApplication.translate("IscApp", u"Step", None))
        self.actionOpenDemo.setText(QCoreApplication.translate("IscApp", u"Demo", None))
        self.browseDemoBtn.setText(QCoreApplication.translate("IscApp", u"Demo", None))
        self.browseScriptBtn.setText(QCoreApplication.translate("IscApp", u"Script", None))
        self.browseAudioBtn.setText(QCoreApplication.translate("IscApp", u"Audio", None))
        ___qtreewidgetitem = self.demoListTreeWidget.headerItem()
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("IscApp", u"Script", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("IscApp", u"Audio", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("IscApp", u"Demo", None));
        self.infoBtn.setText(QCoreApplication.translate("IscApp", u"Info", None))
        self.loadScriptBtn.setText(QCoreApplication.translate("IscApp", u"Load Script", None))
        self.loadAudioBtn.setText(QCoreApplication.translate("IscApp", u"Load audio", None))
        self.removeDemoBtn.setText(QCoreApplication.translate("IscApp", u"Remove", None))
        self.addDemoBtn.setText(QCoreApplication.translate("IscApp", u"Add Demo", None))
        self.assetsTabs.setTabText(self.assetsTabs.indexOf(self.demoList), QCoreApplication.translate("IscApp", u"Demo", None))
#if QT_CONFIG(tooltip)
        self.assetsTabs.setTabToolTip(self.assetsTabs.indexOf(self.demoList), QCoreApplication.translate("IscApp", u"Demo information", None))
#endif // QT_CONFIG(tooltip)
        self.assetsTabs.setTabText(self.assetsTabs.indexOf(self.scriptOverviewTab), QCoreApplication.translate("IscApp", u"Script", None))
        self.assetsTabs.setTabText(self.assetsTabs.indexOf(self.audioOverviewTab), QCoreApplication.translate("IscApp", u"Audio", None))
        ___qtreewidgetitem1 = self.stepsTreeWidget.headerItem()
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("IscApp", u"Target", None));
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("IscApp", u"Operation", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("IscApp", u"#", None));
        self.stepDownBtn.setText(QCoreApplication.translate("IscApp", u"<", None))
        self.stepUpBtn.setText(QCoreApplication.translate("IscApp", u">", None))
        self.removeStepBtn.setText(QCoreApplication.translate("IscApp", u"-", None))
        self.addStepBtn.setText(QCoreApplication.translate("IscApp", u"+", None))
        self.runBtn.setText(QCoreApplication.translate("IscApp", u"Run", None))
        self.opsTabs.setTabText(self.opsTabs.indexOf(self.stepsTab), QCoreApplication.translate("IscApp", u"Steps", None))
        self.opsTabs.setTabText(self.opsTabs.indexOf(self.optionsTab), QCoreApplication.translate("IscApp", u"Options", None))
        self.opsTabs.setTabText(self.opsTabs.indexOf(self.templatesTab), QCoreApplication.translate("IscApp", u"Templates", None))
        self.demoTreeBox.setTitle(QCoreApplication.translate("IscApp", u"Demo (None loaded)", None))
        ___qtreewidgetitem2 = self.demoTreeWidget.headerItem()
        ___qtreewidgetitem2.setText(2, QCoreApplication.translate("IscApp", u"CI", None));
        ___qtreewidgetitem2.setText(1, QCoreApplication.translate("IscApp", u"TP", None));
        self.demoDuplicateBtn.setText(QCoreApplication.translate("IscApp", u"Duplicate", None))
        self.demoInsertSectionBtn.setText(QCoreApplication.translate("IscApp", u"Insert section", None))
        self.demoDeleteBtn.setText(QCoreApplication.translate("IscApp", u"-", None))
        self.demoAddStepBtn.setText(QCoreApplication.translate("IscApp", u"+", None))
        self.demoOverflowBtn.setText(QCoreApplication.translate("IscApp", u"...", None))
        self.dataFrame.setTitle(QCoreApplication.translate("IscApp", u"Metadata", None))
        ___qtreewidgetitem3 = self.metadataTreeWidget.headerItem()
        ___qtreewidgetitem3.setText(1, QCoreApplication.translate("IscApp", u"Value", None));
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("IscApp", u"Property", None));
        self.pushButton_2.setText(QCoreApplication.translate("IscApp", u"Set animated", None))
        self.pushButton.setText(QCoreApplication.translate("IscApp", u"Add highlight", None))
        self.toolButton.setText(QCoreApplication.translate("IscApp", u"...", None))
        ___qtreewidgetitem4 = self.sectionDataTreeW.headerItem()
        ___qtreewidgetitem4.setText(1, QCoreApplication.translate("IscApp", u"Value", None));
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("IscApp", u"Property", None));
        self.pushButton_4.setText(QCoreApplication.translate("IscApp", u"Set Animated", None))
        self.pushButton_3.setText(QCoreApplication.translate("IscApp", u"Set Guided", None))
        self.pushButton_5.setText(QCoreApplication.translate("IscApp", u"Set Scroll", None))
        self.toolButton_2.setText(QCoreApplication.translate("IscApp", u"...", None))
        self.centralTabs.setTabText(self.centralTabs.indexOf(self.centralTabsPage1_2), QCoreApplication.translate("IscApp", u"Demo Utilities", None))
        self.centralTabs.setTabText(self.centralTabs.indexOf(self.centralTabsPage2_2), QCoreApplication.translate("IscApp", u"Script Studio", None))
        self.centralTabs.setTabText(self.centralTabs.indexOf(self.centralTabsPage3), QCoreApplication.translate("IscApp", u"Production", None))
        self.menuFile.setTitle(QCoreApplication.translate("IscApp", u"File", None))
        self.menuExport_2.setTitle(QCoreApplication.translate("IscApp", u"Export...", None))
        self.menuNew.setTitle(QCoreApplication.translate("IscApp", u"New...", None))
        self.menuOpen.setTitle(QCoreApplication.translate("IscApp", u"Open...", None))
        self.menuEdit.setTitle(QCoreApplication.translate("IscApp", u"Edit", None))
        self.menuSelect_all.setTitle(QCoreApplication.translate("IscApp", u"Select all...", None))
        self.menuSelect_associated.setTitle(QCoreApplication.translate("IscApp", u"Select associated...", None))
        self.menuView.setTitle(QCoreApplication.translate("IscApp", u"View", None))
        self.menuZoom.setTitle(QCoreApplication.translate("IscApp", u"Zoom...", None))
        self.menuTools.setTitle(QCoreApplication.translate("IscApp", u"Tools", None))
        self.menuAudio.setTitle(QCoreApplication.translate("IscApp", u"Audio", None))
        self.menuImage.setTitle(QCoreApplication.translate("IscApp", u"Image", None))
        self.menuInsert.setTitle(QCoreApplication.translate("IscApp", u"Paste...", None))
        self.menuShell.setTitle(QCoreApplication.translate("IscApp", u"Shell...", None))
        self.menuDemo.setTitle(QCoreApplication.translate("IscApp", u"Demo", None))
        self.menuScript.setTitle(QCoreApplication.translate("IscApp", u"Script", None))
        self.menuCheck_script_for.setTitle(QCoreApplication.translate("IscApp", u"Check script for...", None))
        self.menuClear.setTitle(QCoreApplication.translate("IscApp", u"Clear...", None))
        self.menuWeb.setTitle(QCoreApplication.translate("IscApp", u"Web", None))
        self.menuSection.setTitle(QCoreApplication.translate("IscApp", u"Section...", None))
        self.menuPacing.setTitle(QCoreApplication.translate("IscApp", u"Pacing...", None))
        self.menuAudio_2.setTitle(QCoreApplication.translate("IscApp", u"Audio...", None))
        self.menuStep.setTitle(QCoreApplication.translate("IscApp", u"Step...", None))
        self.menuAudio_3.setTitle(QCoreApplication.translate("IscApp", u"Audio...", None))
        self.menuPacing_2.setTitle(QCoreApplication.translate("IscApp", u"Pacing...", None))
        self.menuImage_2.setTitle(QCoreApplication.translate("IscApp", u"Image...", None))
        self.menuWindow.setTitle(QCoreApplication.translate("IscApp", u"Window", None))
        self.menuHelp.setTitle(QCoreApplication.translate("IscApp", u"Help", None))
        self.menuHow_do_I.setTitle(QCoreApplication.translate("IscApp", u"How do I...", None))
    # retranslateUi

