# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_IscApp(object):
    def setupUi(self, IscApp):
        if not IscApp.objectName():
            IscApp.setObjectName(u"IscApp")
        IscApp.resize(1440, 923)
        IscApp.setCursor(QCursor(Qt.ArrowCursor))
        IscApp.setMouseTracking(True)
        self.actionUndo = QAction(IscApp)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(IscApp)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionView_statusbar = QAction(IscApp)
        self.actionView_statusbar.setObjectName(u"actionView_statusbar")
        self.actionView_statusbar.setCheckable(True)
        self.actionView_statusbar.setChecked(True)
        self.actionView_step_preview = QAction(IscApp)
        self.actionView_step_preview.setObjectName(u"actionView_step_preview")
        self.actionView_step_preview.setCheckable(True)
        self.actionView_step_preview.setChecked(True)
        self.actionInsert = QAction(IscApp)
        self.actionInsert.setObjectName(u"actionInsert")
        self.actionShell_Image = QAction(IscApp)
        self.actionShell_Image.setObjectName(u"actionShell_Image")
        self.actionSection_steps = QAction(IscApp)
        self.actionSection_steps.setObjectName(u"actionSection_steps")
        self.actionAttach_audio = QAction(IscApp)
        self.actionAttach_audio.setObjectName(u"actionAttach_audio")
        self.actionBulk_crop = QAction(IscApp)
        self.actionBulk_crop.setObjectName(u"actionBulk_crop")
        self.actionView_demo_in_folder = QAction(IscApp)
        self.actionView_demo_in_folder.setObjectName(u"actionView_demo_in_folder")
        self.actionLoad_tool_state = QAction(IscApp)
        self.actionLoad_tool_state.setObjectName(u"actionLoad_tool_state")
        self.actionSave_tool_state = QAction(IscApp)
        self.actionSave_tool_state.setObjectName(u"actionSave_tool_state")
        self.actionOpen_DemoMate = QAction(IscApp)
        self.actionOpen_DemoMate.setObjectName(u"actionOpen_DemoMate")
        self.actionOpen_Cloudguides_Packaging = QAction(IscApp)
        self.actionOpen_Cloudguides_Packaging.setObjectName(u"actionOpen_Cloudguides_Packaging")
        self.actionAbout = QAction(IscApp)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionHelp_2 = QAction(IscApp)
        self.actionHelp_2.setObjectName(u"actionHelp_2")
        self.actionImage_Insert = QAction(IscApp)
        self.actionImage_Insert.setObjectName(u"actionImage_Insert")
        self.actionImage_Shelling = QAction(IscApp)
        self.actionImage_Shelling.setObjectName(u"actionImage_Shelling")
        self.actionHelp_3 = QAction(IscApp)
        self.actionHelp_3.setObjectName(u"actionHelp_3")
        self.actionBulk_insert_image = QAction(IscApp)
        self.actionBulk_insert_image.setObjectName(u"actionBulk_insert_image")
        self.actionBulk_shell_steps = QAction(IscApp)
        self.actionBulk_shell_steps.setObjectName(u"actionBulk_shell_steps")
        self.actionBulk_crop_step_assets = QAction(IscApp)
        self.actionBulk_crop_step_assets.setObjectName(u"actionBulk_crop_step_assets")
        self.actionAttach_audio_to_demo = QAction(IscApp)
        self.actionAttach_audio_to_demo.setObjectName(u"actionAttach_audio_to_demo")
        self.actionClose = QAction(IscApp)
        self.actionClose.setObjectName(u"actionClose")
        self.actionClose_2 = QAction(IscApp)
        self.actionClose_2.setObjectName(u"actionClose_2")
        self.actionFrom_demo_file = QAction(IscApp)
        self.actionFrom_demo_file.setObjectName(u"actionFrom_demo_file")
        self.actionFrom_exe_installer = QAction(IscApp)
        self.actionFrom_exe_installer.setObjectName(u"actionFrom_exe_installer")
        self.actionFrom_docx_file = QAction(IscApp)
        self.actionFrom_docx_file.setObjectName(u"actionFrom_docx_file")
        self.actionFrom_scripts_folder = QAction(IscApp)
        self.actionFrom_scripts_folder.setObjectName(u"actionFrom_scripts_folder")
        self.actionOverwrite = QAction(IscApp)
        self.actionOverwrite.setObjectName(u"actionOverwrite")
        self.actionMerge_demos = QAction(IscApp)
        self.actionMerge_demos.setObjectName(u"actionMerge_demos")
        self.actionLoad_audio_directory = QAction(IscApp)
        self.actionLoad_audio_directory.setObjectName(u"actionLoad_audio_directory")
        self.actionLoad_soundbite = QAction(IscApp)
        self.actionLoad_soundbite.setObjectName(u"actionLoad_soundbite")
        self.actionEdit_audio = QAction(IscApp)
        self.actionEdit_audio.setObjectName(u"actionEdit_audio")
        self.actionAttach_audio_to_demo_2 = QAction(IscApp)
        self.actionAttach_audio_to_demo_2.setObjectName(u"actionAttach_audio_to_demo_2")
        self.actionBulk_edit_demo_audio = QAction(IscApp)
        self.actionBulk_edit_demo_audio.setObjectName(u"actionBulk_edit_demo_audio")
        self.actionEdit_step_audio = QAction(IscApp)
        self.actionEdit_step_audio.setObjectName(u"actionEdit_step_audio")
        self.actionBulk_paste_image = QAction(IscApp)
        self.actionBulk_paste_image.setObjectName(u"actionBulk_paste_image")
        self.actionBulk_image_paste_wizard = QAction(IscApp)
        self.actionBulk_image_paste_wizard.setObjectName(u"actionBulk_image_paste_wizard")
        self.actionBulk_shell_demo_assets = QAction(IscApp)
        self.actionBulk_shell_demo_assets.setObjectName(u"actionBulk_shell_demo_assets")
        self.actionSection_demo = QAction(IscApp)
        self.actionSection_demo.setObjectName(u"actionSection_demo")
        self.actionBulk_resize_demo_assets = QAction(IscApp)
        self.actionBulk_resize_demo_assets.setObjectName(u"actionBulk_resize_demo_assets")
        self.actionBulk_crop_demo_assets = QAction(IscApp)
        self.actionBulk_crop_demo_assets.setObjectName(u"actionBulk_crop_demo_assets")
        self.actionPacing_wizard = QAction(IscApp)
        self.actionPacing_wizard.setObjectName(u"actionPacing_wizard")
        self.actionCompose_demos = QAction(IscApp)
        self.actionCompose_demos.setObjectName(u"actionCompose_demos")
        self.actionBulk_edit_demo_metadata = QAction(IscApp)
        self.actionBulk_edit_demo_metadata.setObjectName(u"actionBulk_edit_demo_metadata")
        self.actionLoad_script = QAction(IscApp)
        self.actionLoad_script.setObjectName(u"actionLoad_script")
        self.actionConvert_script = QAction(IscApp)
        self.actionConvert_script.setObjectName(u"actionConvert_script")
        self.actionSpelling_errors = QAction(IscApp)
        self.actionSpelling_errors.setObjectName(u"actionSpelling_errors")
        self.actionGrammar_errors = QAction(IscApp)
        self.actionGrammar_errors.setObjectName(u"actionGrammar_errors")
        self.actionProduction_notes = QAction(IscApp)
        self.actionProduction_notes.setObjectName(u"actionProduction_notes")
        self.actionTalking_points = QAction(IscApp)
        self.actionTalking_points.setObjectName(u"actionTalking_points")
        self.actionClick_instructions = QAction(IscApp)
        self.actionClick_instructions.setObjectName(u"actionClick_instructions")
        self.actionPackage_demo = QAction(IscApp)
        self.actionPackage_demo.setObjectName(u"actionPackage_demo")
        self.actionSingle_image = QAction(IscApp)
        self.actionSingle_image.setObjectName(u"actionSingle_image")
        self.actionMultiple_images = QAction(IscApp)
        self.actionMultiple_images.setObjectName(u"actionMultiple_images")
        self.actionImage_insert_wizar = QAction(IscApp)
        self.actionImage_insert_wizar.setObjectName(u"actionImage_insert_wizar")
        self.actionAdd_background_image = QAction(IscApp)
        self.actionAdd_background_image.setObjectName(u"actionAdd_background_image")
        self.actionAdd_background_and_wrapper = QAction(IscApp)
        self.actionAdd_background_and_wrapper.setObjectName(u"actionAdd_background_and_wrapper")
        self.actionShell_wizard = QAction(IscApp)
        self.actionShell_wizard.setObjectName(u"actionShell_wizard")
        self.actionCrop = QAction(IscApp)
        self.actionCrop.setObjectName(u"actionCrop")
        self.actionResize = QAction(IscApp)
        self.actionResize.setObjectName(u"actionResize")
        self.actionLoad_operation = QAction(IscApp)
        self.actionLoad_operation.setObjectName(u"actionLoad_operation")
        self.actionSave_operation = QAction(IscApp)
        self.actionSave_operation.setObjectName(u"actionSave_operation")
        self.actionClose_3 = QAction(IscApp)
        self.actionClose_3.setObjectName(u"actionClose_3")
        self.actionZoom_in = QAction(IscApp)
        self.actionZoom_in.setObjectName(u"actionZoom_in")
        self.actionAdd_scroll_section = QAction(IscApp)
        self.actionAdd_scroll_section.setObjectName(u"actionAdd_scroll_section")
        self.actionOpen_assets_folder = QAction(IscApp)
        self.actionOpen_assets_folder.setObjectName(u"actionOpen_assets_folder")
        self.actionUpload_to_CloudGuides = QAction(IscApp)
        self.actionUpload_to_CloudGuides.setObjectName(u"actionUpload_to_CloudGuides")
        self.actionSections = QAction(IscApp)
        self.actionSections.setObjectName(u"actionSections")
        self.actionsteps = QAction(IscApp)
        self.actionsteps.setObjectName(u"actionsteps")
        self.actionSection = QAction(IscApp)
        self.actionSection.setObjectName(u"actionSection")
        self.actionSteps_in_section = QAction(IscApp)
        self.actionSteps_in_section.setObjectName(u"actionSteps_in_section")
        self.actionFirst_step_in_section = QAction(IscApp)
        self.actionFirst_step_in_section.setObjectName(u"actionFirst_step_in_section")
        self.actionSet_section_as_animated = QAction(IscApp)
        self.actionSet_section_as_animated.setObjectName(u"actionSet_section_as_animated")
        self.actionSet_section_as_guided = QAction(IscApp)
        self.actionSet_section_as_guided.setObjectName(u"actionSet_section_as_guided")
        self.actionDelete = QAction(IscApp)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionDuplicate = QAction(IscApp)
        self.actionDuplicate.setObjectName(u"actionDuplicate")
        self.actionDuplicate_as_pacing = QAction(IscApp)
        self.actionDuplicate_as_pacing.setObjectName(u"actionDuplicate_as_pacing")
        self.actionMove = QAction(IscApp)
        self.actionMove.setObjectName(u"actionMove")
        self.actionMove_2 = QAction(IscApp)
        self.actionMove_2.setObjectName(u"actionMove_2")
        self.actionSet_as_animated = QAction(IscApp)
        self.actionSet_as_animated.setObjectName(u"actionSet_as_animated")
        self.actionSet_as_guided = QAction(IscApp)
        self.actionSet_as_guided.setObjectName(u"actionSet_as_guided")
        self.actionSet_as_scroll = QAction(IscApp)
        self.actionSet_as_scroll.setObjectName(u"actionSet_as_scroll")
        self.actionDecrement_step_delay = QAction(IscApp)
        self.actionDecrement_step_delay.setObjectName(u"actionDecrement_step_delay")
        self.actionIncrement_step_delay = QAction(IscApp)
        self.actionIncrement_step_delay.setObjectName(u"actionIncrement_step_delay")
        self.actionAdd_audio_2 = QAction(IscApp)
        self.actionAdd_audio_2.setObjectName(u"actionAdd_audio_2")
        self.actionDelete_audio = QAction(IscApp)
        self.actionDelete_audio.setObjectName(u"actionDelete_audio")
        self.actionEdit_audio_2 = QAction(IscApp)
        self.actionEdit_audio_2.setObjectName(u"actionEdit_audio_2")
        self.actionReplace_audio = QAction(IscApp)
        self.actionReplace_audio.setObjectName(u"actionReplace_audio")
        self.actionView_metadata = QAction(IscApp)
        self.actionView_metadata.setObjectName(u"actionView_metadata")
        self.actionAdd_audio_3 = QAction(IscApp)
        self.actionAdd_audio_3.setObjectName(u"actionAdd_audio_3")
        self.actionDelete_audio_2 = QAction(IscApp)
        self.actionDelete_audio_2.setObjectName(u"actionDelete_audio_2")
        self.actionReplace_audio_2 = QAction(IscApp)
        self.actionReplace_audio_2.setObjectName(u"actionReplace_audio_2")
        self.actionEdit_audio_3 = QAction(IscApp)
        self.actionEdit_audio_3.setObjectName(u"actionEdit_audio_3")
        self.actionIncrement_step_delay_2 = QAction(IscApp)
        self.actionIncrement_step_delay_2.setObjectName(u"actionIncrement_step_delay_2")
        self.actionDecrement_step_delay_2 = QAction(IscApp)
        self.actionDecrement_step_delay_2.setObjectName(u"actionDecrement_step_delay_2")
        self.actionPreview = QAction(IscApp)
        self.actionPreview.setObjectName(u"actionPreview")
        self.actionView_in_folder = QAction(IscApp)
        self.actionView_in_folder.setObjectName(u"actionView_in_folder")
        self.actionEdit = QAction(IscApp)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionReplace_image = QAction(IscApp)
        self.actionReplace_image.setObjectName(u"actionReplace_image")
        self.actionView_metadata_2 = QAction(IscApp)
        self.actionView_metadata_2.setObjectName(u"actionView_metadata_2")
        self.actionLoad_SoundBite = QAction(IscApp)
        self.actionLoad_SoundBite.setObjectName(u"actionLoad_SoundBite")
        self.actionFrom_recording = QAction(IscApp)
        self.actionFrom_recording.setObjectName(u"actionFrom_recording")
        self.actionAs_new_version = QAction(IscApp)
        self.actionAs_new_version.setObjectName(u"actionAs_new_version")
        self.actionAs_new_round = QAction(IscApp)
        self.actionAs_new_round.setObjectName(u"actionAs_new_round")
        self.actionExport_to_installer = QAction(IscApp)
        self.actionExport_to_installer.setObjectName(u"actionExport_to_installer")
        self.actionExport_to_Cloudguide = QAction(IscApp)
        self.actionExport_to_Cloudguide.setObjectName(u"actionExport_to_Cloudguide")
        self.actionTo_installer = QAction(IscApp)
        self.actionTo_installer.setObjectName(u"actionTo_installer")
        self.actionTo_Cloudguide = QAction(IscApp)
        self.actionTo_Cloudguide.setObjectName(u"actionTo_Cloudguide")
        self.actionOverwrite_2 = QAction(IscApp)
        self.actionOverwrite_2.setObjectName(u"actionOverwrite_2")
        self.actionAs_new_version_2 = QAction(IscApp)
        self.actionAs_new_version_2.setObjectName(u"actionAs_new_version_2")
        self.actionAs_new_round_2 = QAction(IscApp)
        self.actionAs_new_round_2.setObjectName(u"actionAs_new_round_2")
        self.actionAs_txt = QAction(IscApp)
        self.actionAs_txt.setObjectName(u"actionAs_txt")
        self.actionTo_new_directory = QAction(IscApp)
        self.actionTo_new_directory.setObjectName(u"actionTo_new_directory")
        self.actionOverwrite_3 = QAction(IscApp)
        self.actionOverwrite_3.setObjectName(u"actionOverwrite_3")
        self.actionClose_window = QAction(IscApp)
        self.actionClose_window.setObjectName(u"actionClose_window")
        self.actionReset_demo = QAction(IscApp)
        self.actionReset_demo.setObjectName(u"actionReset_demo")
        self.actionNew = QAction(IscApp)
        self.actionNew.setObjectName(u"actionNew")
        self.actionNew_operation = QAction(IscApp)
        self.actionNew_operation.setObjectName(u"actionNew_operation")
        self.actionAdd_step = QAction(IscApp)
        self.actionAdd_step.setObjectName(u"actionAdd_step")
        self.actionPreferences = QAction(IscApp)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionAdd_text_box = QAction(IscApp)
        self.actionAdd_text_box.setObjectName(u"actionAdd_text_box")
        self.actionAdd_highlight = QAction(IscApp)
        self.actionAdd_highlight.setObjectName(u"actionAdd_highlight")
        self.actionAdd_jump_box = QAction(IscApp)
        self.actionAdd_jump_box.setObjectName(u"actionAdd_jump_box")
        self.actionSet_animated = QAction(IscApp)
        self.actionSet_animated.setObjectName(u"actionSet_animated")
        self.actionSet_guided = QAction(IscApp)
        self.actionSet_guided.setObjectName(u"actionSet_guided")
        self.actionEdit_XML = QAction(IscApp)
        self.actionEdit_XML.setObjectName(u"actionEdit_XML")
        self.actionFrom_capture = QAction(IscApp)
        self.actionFrom_capture.setObjectName(u"actionFrom_capture")
        self.actionCapture_image_edt_macro = QAction(IscApp)
        self.actionCapture_image_edt_macro.setObjectName(u"actionCapture_image_edt_macro")
        self.actionNew_tab = QAction(IscApp)
        self.actionNew_tab.setObjectName(u"actionNew_tab")
        self.actionNew_2 = QAction(IscApp)
        self.actionNew_2.setObjectName(u"actionNew_2")
        self.actionTo_new_version = QAction(IscApp)
        self.actionTo_new_version.setObjectName(u"actionTo_new_version")
        self.actionTo_new_round = QAction(IscApp)
        self.actionTo_new_round.setObjectName(u"actionTo_new_round")
        self.actionSteps = QAction(IscApp)
        self.actionSteps.setObjectName(u"actionSteps")
        self.actionOverwrite_existing = QAction(IscApp)
        self.actionOverwrite_existing.setObjectName(u"actionOverwrite_existing")
        self.actionSave = QAction(IscApp)
        self.actionSave.setObjectName(u"actionSave")
        self.actionDemo = QAction(IscApp)
        self.actionDemo.setObjectName(u"actionDemo")
        self.actionAudio = QAction(IscApp)
        self.actionAudio.setObjectName(u"actionAudio")
        self.actionScript = QAction(IscApp)
        self.actionScript.setObjectName(u"actionScript")
        self.actionView_menubar = QAction(IscApp)
        self.actionView_menubar.setObjectName(u"actionView_menubar")
        self.actionView_menubar.setCheckable(True)
        self.actionView_in_file_explorer = QAction(IscApp)
        self.actionView_in_file_explorer.setObjectName(u"actionView_in_file_explorer")
        self.actionView_menubar_2 = QAction(IscApp)
        self.actionView_menubar_2.setObjectName(u"actionView_menubar_2")
        self.actionView_menubar_2.setCheckable(True)
        self.actionZoom_out = QAction(IscApp)
        self.actionZoom_out.setObjectName(u"actionZoom_out")
        self.actionReset_zoom = QAction(IscApp)
        self.actionReset_zoom.setObjectName(u"actionReset_zoom")
        self.actionNewStep = QAction(IscApp)
        self.actionNewStep.setObjectName(u"actionNewStep")
        self.actionOpenDemo = QAction(IscApp)
        self.actionOpenDemo.setObjectName(u"actionOpenDemo")
        self.menubar = QMenuBar(IscApp)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1440, 22))
        self.menubar.setDefaultUp(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExport_2 = QMenu(self.menuFile)
        self.menuExport_2.setObjectName(u"menuExport_2")
        self.menuNew = QMenu(self.menuFile)
        self.menuNew.setObjectName(u"menuNew")
        self.menuOpen = QMenu(self.menuFile)
        self.menuOpen.setObjectName(u"menuOpen")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSelect_all = QMenu(self.menuEdit)
        self.menuSelect_all.setObjectName(u"menuSelect_all")
        self.menuSelect_associated = QMenu(self.menuEdit)
        self.menuSelect_associated.setObjectName(u"menuSelect_associated")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuView.setTearOffEnabled(False)
        self.menuView.setToolTipsVisible(True)
        self.menuZoom = QMenu(self.menuView)
        self.menuZoom.setObjectName(u"menuZoom")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuAudio = QMenu(self.menuTools)
        self.menuAudio.setObjectName(u"menuAudio")
        self.menuImage = QMenu(self.menuTools)
        self.menuImage.setObjectName(u"menuImage")
        self.menuInsert = QMenu(self.menuImage)
        self.menuInsert.setObjectName(u"menuInsert")
        self.menuShell = QMenu(self.menuImage)
        self.menuShell.setObjectName(u"menuShell")
        self.menuDemo = QMenu(self.menuTools)
        self.menuDemo.setObjectName(u"menuDemo")
        self.menuScript = QMenu(self.menuTools)
        self.menuScript.setObjectName(u"menuScript")
        self.menuCheck_script_for = QMenu(self.menuScript)
        self.menuCheck_script_for.setObjectName(u"menuCheck_script_for")
        self.menuClear = QMenu(self.menuScript)
        self.menuClear.setObjectName(u"menuClear")
        self.menuWeb = QMenu(self.menuTools)
        self.menuWeb.setObjectName(u"menuWeb")
        self.menuSection = QMenu(self.menuTools)
        self.menuSection.setObjectName(u"menuSection")
        self.menuPacing = QMenu(self.menuSection)
        self.menuPacing.setObjectName(u"menuPacing")
        self.menuAudio_2 = QMenu(self.menuSection)
        self.menuAudio_2.setObjectName(u"menuAudio_2")
        self.menuStep = QMenu(self.menuTools)
        self.menuStep.setObjectName(u"menuStep")
        self.menuAudio_3 = QMenu(self.menuStep)
        self.menuAudio_3.setObjectName(u"menuAudio_3")
        self.menuPacing_2 = QMenu(self.menuStep)
        self.menuPacing_2.setObjectName(u"menuPacing_2")
        self.menuImage_2 = QMenu(self.menuStep)
        self.menuImage_2.setObjectName(u"menuImage_2")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuHow_do_I = QMenu(self.menuHelp)
        self.menuHow_do_I.setObjectName(u"menuHow_do_I")
        IscApp.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(IscApp)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setMinimumSize(QSize(0, 30))
        self.statusbar.setSizeGripEnabled(False)
        IscApp.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.menuExport_2.menuAction())
        self.menuExport_2.addAction(self.actionDemo)
        self.menuExport_2.addAction(self.actionAudio)
        self.menuExport_2.addAction(self.actionScript)
        self.menuNew.addAction(self.actionNewStep)
        self.menuOpen.addAction(self.actionOpenDemo)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuSelect_all.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuSelect_associated.menuAction())
        self.menuSelect_all.addAction(self.actionSections)
        self.menuSelect_all.addAction(self.actionsteps)
        self.menuSelect_associated.addAction(self.actionSection)
        self.menuSelect_associated.addAction(self.actionSteps_in_section)
        self.menuSelect_associated.addAction(self.actionFirst_step_in_section)
        self.menuView.addAction(self.actionView_statusbar)
        self.menuView.addAction(self.actionView_step_preview)
        self.menuView.addAction(self.actionView_demo_in_folder)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menuView.addAction(self.actionView_menubar)
        self.menuView.addAction(self.actionView_in_file_explorer)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionView_menubar_2)
        self.menuZoom.addAction(self.actionZoom_in)
        self.menuZoom.addAction(self.actionZoom_out)
        self.menuZoom.addAction(self.actionReset_zoom)
        self.menuTools.addAction(self.menuAudio.menuAction())
        self.menuTools.addAction(self.menuImage.menuAction())
        self.menuTools.addAction(self.menuDemo.menuAction())
        self.menuTools.addAction(self.menuScript.menuAction())
        self.menuTools.addAction(self.menuWeb.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuSection.menuAction())
        self.menuTools.addAction(self.menuStep.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPreferences)
        self.menuAudio.addAction(self.actionAttach_audio_to_demo_2)
        self.menuAudio.addAction(self.actionBulk_edit_demo_audio)
        self.menuAudio.addAction(self.actionEdit_step_audio)
        self.menuImage.addAction(self.actionBulk_paste_image)
        self.menuImage.addAction(self.actionBulk_image_paste_wizard)
        self.menuImage.addAction(self.actionBulk_shell_demo_assets)
        self.menuImage.addAction(self.menuInsert.menuAction())
        self.menuImage.addAction(self.menuShell.menuAction())
        self.menuImage.addAction(self.actionCrop)
        self.menuImage.addAction(self.actionResize)
        self.menuImage.addAction(self.actionCapture_image_edt_macro)
        self.menuInsert.addAction(self.actionSingle_image)
        self.menuInsert.addAction(self.actionMultiple_images)
        self.menuInsert.addAction(self.actionImage_insert_wizar)
        self.menuShell.addAction(self.actionAdd_background_image)
        self.menuShell.addAction(self.actionAdd_background_and_wrapper)
        self.menuShell.addAction(self.actionShell_wizard)
        self.menuDemo.addAction(self.actionSection_demo)
        self.menuDemo.addAction(self.actionPacing_wizard)
        self.menuDemo.addAction(self.actionCompose_demos)
        self.menuDemo.addAction(self.actionBulk_edit_demo_metadata)
        self.menuDemo.addAction(self.actionPackage_demo)
        self.menuDemo.addAction(self.actionAdd_scroll_section)
        self.menuDemo.addAction(self.actionAdd_step)
        self.menuDemo.addAction(self.actionEdit_XML)
        self.menuScript.addAction(self.actionLoad_script)
        self.menuScript.addAction(self.actionConvert_script)
        self.menuScript.addAction(self.menuCheck_script_for.menuAction())
        self.menuScript.addAction(self.menuClear.menuAction())
        self.menuCheck_script_for.addAction(self.actionSpelling_errors)
        self.menuCheck_script_for.addAction(self.actionGrammar_errors)
        self.menuCheck_script_for.addAction(self.actionProduction_notes)
        self.menuClear.addAction(self.actionTalking_points)
        self.menuClear.addAction(self.actionClick_instructions)
        self.menuWeb.addAction(self.actionUpload_to_CloudGuides)
        self.menuSection.addAction(self.actionSet_section_as_animated)
        self.menuSection.addAction(self.actionSet_section_as_guided)
        self.menuSection.addAction(self.actionMove_2)
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.actionSet_as_animated)
        self.menuSection.addAction(self.actionSet_as_guided)
        self.menuSection.addAction(self.actionSet_as_scroll)
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.menuAudio_2.menuAction())
        self.menuSection.addAction(self.menuPacing.menuAction())
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.actionView_metadata)
        self.menuPacing.addAction(self.actionDecrement_step_delay)
        self.menuPacing.addAction(self.actionIncrement_step_delay)
        self.menuAudio_2.addAction(self.actionAdd_audio_2)
        self.menuAudio_2.addAction(self.actionDelete_audio)
        self.menuAudio_2.addAction(self.actionEdit_audio_2)
        self.menuAudio_2.addAction(self.actionReplace_audio)
        self.menuStep.addAction(self.actionDelete)
        self.menuStep.addAction(self.actionDuplicate)
        self.menuStep.addAction(self.actionDuplicate_as_pacing)
        self.menuStep.addAction(self.actionMove)
        self.menuStep.addSeparator()
        self.menuStep.addAction(self.menuAudio_3.menuAction())
        self.menuStep.addAction(self.menuPacing_2.menuAction())
        self.menuStep.addAction(self.menuImage_2.menuAction())
        self.menuStep.addSeparator()
        self.menuStep.addAction(self.actionAdd_text_box)
        self.menuStep.addAction(self.actionAdd_highlight)
        self.menuStep.addAction(self.actionAdd_jump_box)
        self.menuStep.addSeparator()
        self.menuStep.addAction(self.actionSet_animated)
        self.menuStep.addAction(self.actionSet_guided)
        self.menuStep.addAction(self.actionFrom_capture)
        self.menuAudio_3.addAction(self.actionAdd_audio_3)
        self.menuAudio_3.addAction(self.actionDelete_audio_2)
        self.menuAudio_3.addAction(self.actionReplace_audio_2)
        self.menuAudio_3.addAction(self.actionEdit_audio_3)
        self.menuPacing_2.addAction(self.actionIncrement_step_delay_2)
        self.menuPacing_2.addAction(self.actionDecrement_step_delay_2)
        self.menuImage_2.addAction(self.actionPreview)
        self.menuImage_2.addAction(self.actionView_in_folder)
        self.menuImage_2.addAction(self.actionEdit)
        self.menuImage_2.addAction(self.actionReplace_image)
        self.menuWindow.addAction(self.actionOpen_DemoMate)
        self.menuWindow.addAction(self.actionOpen_Cloudguides_Packaging)
        self.menuWindow.addAction(self.actionClose)
        self.menuWindow.addAction(self.actionOpen_assets_folder)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.menuHow_do_I.menuAction())
        self.menuHelp.addSeparator()
        self.menuHow_do_I.addAction(self.actionBulk_insert_image)
        self.menuHow_do_I.addAction(self.actionBulk_shell_steps)
        self.menuHow_do_I.addAction(self.actionBulk_crop_step_assets)
        self.menuHow_do_I.addAction(self.actionAttach_audio_to_demo)

        self.retranslateUi(IscApp)

        QMetaObject.connectSlotsByName(IscApp)
    # setupUi

    def retranslateUi(self, IscApp):
        IscApp.setWindowTitle(QCoreApplication.translate("IscApp", u"IscApp", None))
        self.actionUndo.setText(QCoreApplication.translate("IscApp", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("IscApp", u"Redo", None))
        self.actionView_statusbar.setText(QCoreApplication.translate("IscApp", u"View statusbar", None))
        self.actionView_step_preview.setText(QCoreApplication.translate("IscApp", u"View step preview", None))
        self.actionInsert.setText(QCoreApplication.translate("IscApp", u"Insert Image", None))
        self.actionShell_Image.setText(QCoreApplication.translate("IscApp", u"Shell Image", None))
        self.actionSection_steps.setText(QCoreApplication.translate("IscApp", u"Section steps", None))
        self.actionAttach_audio.setText(QCoreApplication.translate("IscApp", u"Attach audio", None))
        self.actionBulk_crop.setText(QCoreApplication.translate("IscApp", u"Bulk crop", None))
        self.actionView_demo_in_folder.setText(QCoreApplication.translate("IscApp", u"View demo in folder", None))
        self.actionLoad_tool_state.setText(QCoreApplication.translate("IscApp", u"Load tool state", None))
        self.actionSave_tool_state.setText(QCoreApplication.translate("IscApp", u"Save tool state", None))
        self.actionOpen_DemoMate.setText(QCoreApplication.translate("IscApp", u"Open Demo in DemoMate", None))
        self.actionOpen_Cloudguides_Packaging.setText(QCoreApplication.translate("IscApp", u"Open Cloudguides Packaging tool", None))
        self.actionAbout.setText(QCoreApplication.translate("IscApp", u"About", None))
        self.actionHelp_2.setText(QCoreApplication.translate("IscApp", u"Help", None))
        self.actionImage_Insert.setText(QCoreApplication.translate("IscApp", u"Insert image", None))
        self.actionImage_Shelling.setText(QCoreApplication.translate("IscApp", u"Shell image", None))
        self.actionHelp_3.setText(QCoreApplication.translate("IscApp", u"Help", None))
        self.actionBulk_insert_image.setText(QCoreApplication.translate("IscApp", u"Bulk insert image into step assets", None))
        self.actionBulk_shell_steps.setText(QCoreApplication.translate("IscApp", u"Bulk shell step assets", None))
        self.actionBulk_crop_step_assets.setText(QCoreApplication.translate("IscApp", u"Bulk crop step assets", None))
        self.actionAttach_audio_to_demo.setText(QCoreApplication.translate("IscApp", u"Attach audio to demo", None))
        self.actionClose.setText(QCoreApplication.translate("IscApp", u"Open folder containing demo", None))
        self.actionClose_2.setText(QCoreApplication.translate("IscApp", u"Close", None))
        self.actionFrom_demo_file.setText(QCoreApplication.translate("IscApp", u"From .demo file", None))
        self.actionFrom_exe_installer.setText(QCoreApplication.translate("IscApp", u"From .exe installer", None))
        self.actionFrom_docx_file.setText(QCoreApplication.translate("IscApp", u"From .docx file", None))
        self.actionFrom_scripts_folder.setText(QCoreApplication.translate("IscApp", u"From scripts folder", None))
        self.actionOverwrite.setText(QCoreApplication.translate("IscApp", u"Overwrite", None))
        self.actionMerge_demos.setText(QCoreApplication.translate("IscApp", u"Merge demos", None))
        self.actionLoad_audio_directory.setText(QCoreApplication.translate("IscApp", u"Load Audio", None))
        self.actionLoad_soundbite.setText(QCoreApplication.translate("IscApp", u"Load from .zip", None))
        self.actionEdit_audio.setText(QCoreApplication.translate("IscApp", u"Edit audio", None))
        self.actionAttach_audio_to_demo_2.setText(QCoreApplication.translate("IscApp", u"Attach audio to demo", None))
        self.actionBulk_edit_demo_audio.setText(QCoreApplication.translate("IscApp", u"Bulk edit demo audio", None))
        self.actionEdit_step_audio.setText(QCoreApplication.translate("IscApp", u"Edit step audio", None))
        self.actionBulk_paste_image.setText(QCoreApplication.translate("IscApp", u"Bulk paste image", None))
        self.actionBulk_image_paste_wizard.setText(QCoreApplication.translate("IscApp", u"Bulk image paste wizard", None))
        self.actionBulk_shell_demo_assets.setText(QCoreApplication.translate("IscApp", u"Bulk shell demo assets", None))
        self.actionSection_demo.setText(QCoreApplication.translate("IscApp", u"Section demo", None))
        self.actionBulk_resize_demo_assets.setText(QCoreApplication.translate("IscApp", u"Bulk resize demo assets", None))
        self.actionBulk_crop_demo_assets.setText(QCoreApplication.translate("IscApp", u"Bulk crop demo assets", None))
        self.actionPacing_wizard.setText(QCoreApplication.translate("IscApp", u"Open pacing wizard", None))
        self.actionCompose_demos.setText(QCoreApplication.translate("IscApp", u"Compose demos", None))
        self.actionBulk_edit_demo_metadata.setText(QCoreApplication.translate("IscApp", u"View/edit metadata", None))
        self.actionLoad_script.setText(QCoreApplication.translate("IscApp", u"Load Script", None))
#if QT_CONFIG(shortcut)
        self.actionLoad_script.setShortcut(QCoreApplication.translate("IscApp", u"Alt+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionConvert_script.setText(QCoreApplication.translate("IscApp", u"Convert script", None))
        self.actionSpelling_errors.setText(QCoreApplication.translate("IscApp", u"Spelling errors", None))
        self.actionGrammar_errors.setText(QCoreApplication.translate("IscApp", u"Grammar errors", None))
        self.actionProduction_notes.setText(QCoreApplication.translate("IscApp", u"Production notes", None))
        self.actionTalking_points.setText(QCoreApplication.translate("IscApp", u"Talking points", None))
        self.actionClick_instructions.setText(QCoreApplication.translate("IscApp", u"Click instructions", None))
        self.actionPackage_demo.setText(QCoreApplication.translate("IscApp", u"Package demo", None))
        self.actionSingle_image.setText(QCoreApplication.translate("IscApp", u"Single image", None))
        self.actionMultiple_images.setText(QCoreApplication.translate("IscApp", u"Multiple images", None))
        self.actionImage_insert_wizar.setText(QCoreApplication.translate("IscApp", u"From asset region", None))
        self.actionAdd_background_image.setText(QCoreApplication.translate("IscApp", u"Add background image", None))
        self.actionAdd_background_and_wrapper.setText(QCoreApplication.translate("IscApp", u"Add background and wrapper", None))
        self.actionShell_wizard.setText(QCoreApplication.translate("IscApp", u"Shell wizard", None))
        self.actionCrop.setText(QCoreApplication.translate("IscApp", u"Crop", None))
        self.actionResize.setText(QCoreApplication.translate("IscApp", u"Resize", None))
        self.actionLoad_operation.setText(QCoreApplication.translate("IscApp", u"Add operation...", None))
        self.actionSave_operation.setText(QCoreApplication.translate("IscApp", u"Load operation...", None))
        self.actionClose_3.setText(QCoreApplication.translate("IscApp", u"Save operation...", None))
        self.actionZoom_in.setText(QCoreApplication.translate("IscApp", u"Zoom in", None))
        self.actionAdd_scroll_section.setText(QCoreApplication.translate("IscApp", u"Add scroll section", None))
        self.actionOpen_assets_folder.setText(QCoreApplication.translate("IscApp", u"Open assets folder", None))
        self.actionUpload_to_CloudGuides.setText(QCoreApplication.translate("IscApp", u"Upload to CloudGuides", None))
        self.actionSections.setText(QCoreApplication.translate("IscApp", u"Sections", None))
        self.actionsteps.setText(QCoreApplication.translate("IscApp", u"Steps", None))
        self.actionSection.setText(QCoreApplication.translate("IscApp", u"Section", None))
        self.actionSteps_in_section.setText(QCoreApplication.translate("IscApp", u"Steps in section", None))
        self.actionFirst_step_in_section.setText(QCoreApplication.translate("IscApp", u"First step in section", None))
        self.actionSet_section_as_animated.setText(QCoreApplication.translate("IscApp", u"Delete", None))
        self.actionSet_section_as_guided.setText(QCoreApplication.translate("IscApp", u"Duplicate", None))
        self.actionDelete.setText(QCoreApplication.translate("IscApp", u"Delete", None))
        self.actionDuplicate.setText(QCoreApplication.translate("IscApp", u"Duplicate", None))
        self.actionDuplicate_as_pacing.setText(QCoreApplication.translate("IscApp", u"Duplicate as pacing", None))
        self.actionMove.setText(QCoreApplication.translate("IscApp", u"Move", None))
        self.actionMove_2.setText(QCoreApplication.translate("IscApp", u"Move", None))
        self.actionSet_as_animated.setText(QCoreApplication.translate("IscApp", u"Set as animated", None))
        self.actionSet_as_guided.setText(QCoreApplication.translate("IscApp", u"Set as guided", None))
        self.actionSet_as_scroll.setText(QCoreApplication.translate("IscApp", u"Set as scroll", None))
        self.actionDecrement_step_delay.setText(QCoreApplication.translate("IscApp", u"Decrement step delay", None))
        self.actionIncrement_step_delay.setText(QCoreApplication.translate("IscApp", u"Increment step delay", None))
        self.actionAdd_audio_2.setText(QCoreApplication.translate("IscApp", u"Add audio", None))
        self.actionDelete_audio.setText(QCoreApplication.translate("IscApp", u"Delete audio", None))
        self.actionEdit_audio_2.setText(QCoreApplication.translate("IscApp", u"Edit audio", None))
        self.actionReplace_audio.setText(QCoreApplication.translate("IscApp", u"Replace audio", None))
        self.actionView_metadata.setText(QCoreApplication.translate("IscApp", u"View metadata", None))
        self.actionAdd_audio_3.setText(QCoreApplication.translate("IscApp", u"Add audio", None))
        self.actionDelete_audio_2.setText(QCoreApplication.translate("IscApp", u"Delete audio", None))
        self.actionReplace_audio_2.setText(QCoreApplication.translate("IscApp", u"Replace audio", None))
        self.actionEdit_audio_3.setText(QCoreApplication.translate("IscApp", u"Edit audio", None))
        self.actionIncrement_step_delay_2.setText(QCoreApplication.translate("IscApp", u"Increment step delay", None))
        self.actionDecrement_step_delay_2.setText(QCoreApplication.translate("IscApp", u"Decrement step delay", None))
        self.actionPreview.setText(QCoreApplication.translate("IscApp", u"Preview image", None))
        self.actionView_in_folder.setText(QCoreApplication.translate("IscApp", u"View in folder", None))
        self.actionEdit.setText(QCoreApplication.translate("IscApp", u"Edit image", None))
        self.actionReplace_image.setText(QCoreApplication.translate("IscApp", u"Replace image", None))
        self.actionView_metadata_2.setText(QCoreApplication.translate("IscApp", u"View metadata", None))
        self.actionLoad_SoundBite.setText(QCoreApplication.translate("IscApp", u"Load soundbite", None))
        self.actionFrom_recording.setText(QCoreApplication.translate("IscApp", u"From recording", None))
        self.actionAs_new_version.setText(QCoreApplication.translate("IscApp", u"As new version", None))
        self.actionAs_new_round.setText(QCoreApplication.translate("IscApp", u"As new round", None))
        self.actionExport_to_installer.setText(QCoreApplication.translate("IscApp", u"Export to installer", None))
        self.actionExport_to_Cloudguide.setText(QCoreApplication.translate("IscApp", u"Export to Cloudguide", None))
        self.actionTo_installer.setText(QCoreApplication.translate("IscApp", u"To installer", None))
        self.actionTo_Cloudguide.setText(QCoreApplication.translate("IscApp", u"To Cloudguide", None))
        self.actionOverwrite_2.setText(QCoreApplication.translate("IscApp", u"Overwrite", None))
        self.actionAs_new_version_2.setText(QCoreApplication.translate("IscApp", u"As new version", None))
        self.actionAs_new_round_2.setText(QCoreApplication.translate("IscApp", u"As new round", None))
        self.actionAs_txt.setText(QCoreApplication.translate("IscApp", u"As .txt", None))
        self.actionTo_new_directory.setText(QCoreApplication.translate("IscApp", u"To new directory", None))
        self.actionOverwrite_3.setText(QCoreApplication.translate("IscApp", u"Overwrite", None))
        self.actionClose_window.setText(QCoreApplication.translate("IscApp", u"Close window", None))
        self.actionReset_demo.setText(QCoreApplication.translate("IscApp", u"Reset demo", None))
        self.actionNew.setText(QCoreApplication.translate("IscApp", u"New...", None))
        self.actionNew_operation.setText(QCoreApplication.translate("IscApp", u"New operation...", None))
        self.actionAdd_step.setText(QCoreApplication.translate("IscApp", u"Add step", None))
        self.actionPreferences.setText(QCoreApplication.translate("IscApp", u"Preferences", None))
        self.actionAdd_text_box.setText(QCoreApplication.translate("IscApp", u"Add text box", None))
        self.actionAdd_highlight.setText(QCoreApplication.translate("IscApp", u"Add highlight", None))
        self.actionAdd_jump_box.setText(QCoreApplication.translate("IscApp", u"Add jump box", None))
        self.actionSet_animated.setText(QCoreApplication.translate("IscApp", u"Set animated", None))
        self.actionSet_guided.setText(QCoreApplication.translate("IscApp", u"Set guided", None))
        self.actionEdit_XML.setText(QCoreApplication.translate("IscApp", u"Edit XML", None))
        self.actionFrom_capture.setText(QCoreApplication.translate("IscApp", u"From capture", None))
        self.actionCapture_image_edt_macro.setText(QCoreApplication.translate("IscApp", u"Capture image edt macro", None))
        self.actionNew_tab.setText(QCoreApplication.translate("IscApp", u"New tab", None))
        self.actionNew_2.setText(QCoreApplication.translate("IscApp", u"New...", None))
        self.actionTo_new_version.setText(QCoreApplication.translate("IscApp", u"To new version", None))
        self.actionTo_new_round.setText(QCoreApplication.translate("IscApp", u"To new round", None))
        self.actionSteps.setText(QCoreApplication.translate("IscApp", u"Steps...", None))
        self.actionOverwrite_existing.setText(QCoreApplication.translate("IscApp", u"Overwrite existing", None))
        self.actionSave.setText(QCoreApplication.translate("IscApp", u"Save...", None))
        self.actionDemo.setText(QCoreApplication.translate("IscApp", u"Demo...", None))
        self.actionAudio.setText(QCoreApplication.translate("IscApp", u"Audio...", None))
        self.actionScript.setText(QCoreApplication.translate("IscApp", u"Script..", None))
        self.actionView_menubar.setText(QCoreApplication.translate("IscApp", u"View console", None))
        self.actionView_in_file_explorer.setText(QCoreApplication.translate("IscApp", u"View in file explorer", None))
#if QT_CONFIG(shortcut)
        self.actionView_in_file_explorer.setShortcut(QCoreApplication.translate("IscApp", u"Ctrl+Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionView_menubar_2.setText(QCoreApplication.translate("IscApp", u"View menubar", None))
#if QT_CONFIG(shortcut)
        self.actionView_menubar_2.setShortcut(QCoreApplication.translate("IscApp", u"Alt+M", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoom_out.setText(QCoreApplication.translate("IscApp", u"Zoom out", None))
        self.actionReset_zoom.setText(QCoreApplication.translate("IscApp", u"Reset zoom", None))
        self.actionNewStep.setText(QCoreApplication.translate("IscApp", u"Step", None))
        self.actionOpenDemo.setText(QCoreApplication.translate("IscApp", u"Demo", None))
        self.menuFile.setTitle(QCoreApplication.translate("IscApp", u"File", None))
        self.menuExport_2.setTitle(QCoreApplication.translate("IscApp", u"Export...", None))
        self.menuNew.setTitle(QCoreApplication.translate("IscApp", u"New...", None))
        self.menuOpen.setTitle(QCoreApplication.translate("IscApp", u"Open...", None))
        self.menuEdit.setTitle(QCoreApplication.translate("IscApp", u"Edit", None))
        self.menuSelect_all.setTitle(QCoreApplication.translate("IscApp", u"Select all...", None))
        self.menuSelect_associated.setTitle(QCoreApplication.translate("IscApp", u"Select associated...", None))
        self.menuView.setTitle(QCoreApplication.translate("IscApp", u"View", None))
        self.menuZoom.setTitle(QCoreApplication.translate("IscApp", u"Zoom...", None))
        self.menuTools.setTitle(QCoreApplication.translate("IscApp", u"Tools", None))
        self.menuAudio.setTitle(QCoreApplication.translate("IscApp", u"Audio", None))
        self.menuImage.setTitle(QCoreApplication.translate("IscApp", u"Image", None))
        self.menuInsert.setTitle(QCoreApplication.translate("IscApp", u"Paste...", None))
        self.menuShell.setTitle(QCoreApplication.translate("IscApp", u"Shell...", None))
        self.menuDemo.setTitle(QCoreApplication.translate("IscApp", u"Demo", None))
        self.menuScript.setTitle(QCoreApplication.translate("IscApp", u"Script", None))
        self.menuCheck_script_for.setTitle(QCoreApplication.translate("IscApp", u"Check script for...", None))
        self.menuClear.setTitle(QCoreApplication.translate("IscApp", u"Clear...", None))
        self.menuWeb.setTitle(QCoreApplication.translate("IscApp", u"Web", None))
        self.menuSection.setTitle(QCoreApplication.translate("IscApp", u"Section...", None))
        self.menuPacing.setTitle(QCoreApplication.translate("IscApp", u"Pacing...", None))
        self.menuAudio_2.setTitle(QCoreApplication.translate("IscApp", u"Audio...", None))
        self.menuStep.setTitle(QCoreApplication.translate("IscApp", u"Step...", None))
        self.menuAudio_3.setTitle(QCoreApplication.translate("IscApp", u"Audio...", None))
        self.menuPacing_2.setTitle(QCoreApplication.translate("IscApp", u"Pacing...", None))
        self.menuImage_2.setTitle(QCoreApplication.translate("IscApp", u"Image...", None))
        self.menuWindow.setTitle(QCoreApplication.translate("IscApp", u"Window", None))
        self.menuHelp.setTitle(QCoreApplication.translate("IscApp", u"Help", None))
        self.menuHow_do_I.setTitle(QCoreApplication.translate("IscApp", u"How do I...", None))
    # retranslateUi

